import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,readdir} from 'node:fs/promises';
import {fixture,uid,sid} from './scheduler-fixture.mjs';
import {bulkShiftChanges,moveShiftDays,linkedShiftIds} from '../src/workflowSchedule.ts';
import {availableChapters} from '../src/walkthroughs.ts';
async function setup(){const f=await fixture();try{const files=await readdir(new URL('../supabase/migrations/',import.meta.url));for(let n=29;n<=38;n++)await f.db.exec(await readFile(new URL('../supabase/migrations/'+files.find(s=>s.startsWith(n.toString().padStart(3,'0')+'_')),import.meta.url),'utf8'));return f}catch(e){await f.db.close();throw e}}
test('bulk changes preserve identities and labels, handle Central dates and reject invalid inputs',()=>{const s={id:'one',person_id:'s:Casey.W',start:'2030-09-02T16:00:00Z',end:'2030-09-02T21:00:00Z',slot:1,job_id:'gsr',qualification_reason:'Prior coaching'};assert.equal(moveShiftDays(s,7).start,'2030-09-09T16:00:00.000Z');assert.equal(bulkShiftChanges([s],['one'],'move',30,'')[0].start,'2030-09-02T16:30:00.000Z');assert.equal(bulkShiftChanges([s],['one'],'assign',0,'s:Alex.L')[0].qualification_reason,'');assert.deepEqual(bulkShiftChanges([s],['one'],'remove',0,''),[]);assert.throws(()=>bulkShiftChanges([s],['missing'],'remove',0,''),/changed/);assert.throws(()=>bulkShiftChanges([s],['one'],'move',721,''),/minutes/);assert.deepEqual([...linkedShiftIds({schedule_meeting_shifts:{one:'m'},training:[{status:'Scheduled',work_shift_id:'two',trainer_shift_id:'three'}],shift_meetings:[]})],['one','two','three']);const d={self:{is_manager:true,is_admin:true}};assert.ok(availableChapters(d,'it').some(c=>c.id==='build_week'));assert.ok(!availableChapters({self:{}},'employee').some(c=>c.id==='build_week'))});
test('favorites, selective copy and attendance enforce ownership, versions, retries and data boundaries',async()=>{const f=await setup();try{
 const rpc=async(n,fn,args)=>(await f.as(n,`select ${fn}(${args.map((_,i)=>'$'+(i+1)).join(',')}) r`,args)).rows[0].r;
 const fav=await rpc(1,'favorites_save',[0,['schedule','training'],sid(700)]);assert.equal(fav.version,1);assert.deepEqual(await rpc(1,'favorites_save',[0,['schedule','training'],sid(700)]),fav);assert.deepEqual((await rpc(2,'favorites_read',[])).pages,[]);await assert.rejects(rpc(4,'favorites_read',[]),/Manager/);await assert.rejects(rpc(2,'favorites_save',[0,['audit'],sid(701)]),/authorized/);await assert.rejects(rpc(1,'favorites_save',[0,[],sid(702)]),/another device/);await assert.rejects(rpc(1,'favorites_save',[1,['schedule','schedule'],sid(703)]),/once/);
 const draft=await f.act(1,'draft',{week:'2030-09-01'}),a=f.shift(1),b=f.shift(2,'s:Alex.L'),meetingShift={...f.shift(3),job_id:null,assignment_type:'training',activity_title:'Meeting'};
 await f.db.query("update private.schedule_revisions set shifts=$1,state='Published' where id=$2",[[a,b,meetingShift],draft.id]);await f.db.query("update private.schedule_weeks set published_id=$1,draft_id=null where week_start='2030-09-01'",[draft.id]);
 const source=await rpc(1,'copy_week_read',['2030-09-01']);assert.equal(source.shifts.length,2);await assert.rejects(rpc(4,'copy_week_read',['2030-09-01']),/Manager/);
 const payload={source_week:'2030-09-01',source_revision:draft.id,week:'2030-09-08',ids:[a.id]};const copied=await rpc(1,'copy_week_save',[payload,sid(704)]);assert.deepEqual(await rpc(1,'copy_week_save',[payload,sid(704)]),copied);const saved=(await f.db.query('select shifts from private.schedule_revisions where id=$1',[copied.id])).rows[0].shifts;assert.equal(saved.length,1);assert.notEqual(saved[0].id,a.id);assert.equal(saved[0].qualification_reason,'');assert.equal(Date.parse(saved[0].start),Date.parse('2030-09-09T16:00Z'));await assert.rejects(rpc(1,'copy_week_save',[{...payload,week:'2030-09-15',source_revision:sid(999)},sid(705)]),/Source publication changed/);await assert.rejects(rpc(1,'copy_week_save',[{...payload,week:'2030-09-15',ids:[meetingShift.id]},sid(706)]),/unavailable/);
 const oldDraft=await f.act(1,'draft',{week:'2020-09-06'}),oldShift={...meetingShift,id:sid(801),start:'2020-09-07T16:00Z',end:'2020-09-07T17:00Z'};
 await f.db.query("update private.schedule_revisions set shifts=$1,state='Published' where id=$2",[[oldShift],oldDraft.id]);await f.db.query("update private.schedule_weeks set published_id=$1,draft_id=null where week_start='2020-09-06'",[oldDraft.id]);await f.db.query("insert into private.staff_meetings(id,title,starts_at,ends_at,mode,week,people,generated,created_by) values($1,'Fictional meeting',$2,$3,'separate','2020-09-06',array['s:Casey.W'],$4,$5)",[sid(800),oldShift.start,oldShift.end,[oldShift],uid(1)]);
 const attendance={id:sid(800),version:0,attendance:{'s:Casey.W':'Attended'}};await assert.rejects(rpc(2,'staff_meeting_attendance_save',[attendance,sid(707)]),/creator/);await assert.rejects(rpc(4,'staff_meeting_attendance_save',[attendance,sid(708)]),/Manager/);await assert.rejects(rpc(1,'staff_meeting_attendance_save',[{...attendance,attendance:{'s:Other.X':'Attended'}},sid(709)]),/Invalid attendee/);
 const historyBefore=(await f.db.query('select count(*)::int n from training_sessions')).rows[0].n;const marked=await rpc(1,'staff_meeting_attendance_save',[attendance,sid(710)]);assert.equal(marked.version,1);assert.deepEqual(await rpc(1,'staff_meeting_attendance_save',[attendance,sid(710)]),marked);await assert.rejects(rpc(1,'staff_meeting_attendance_save',[attendance,sid(711)]),/Attendance changed/);assert.equal((await f.db.query('select count(*)::int n from training_sessions')).rows[0].n,historyBefore);
 const manager=await rpc(1,'staff_meetings_read',[false]);assert.equal(manager.meetings.find(m=>m.id===sid(800)).attendance['s:Casey.W'],'Attended');const employee=await rpc(4,'staff_meetings_read',[false]);assert.ok(employee.meetings.every(m=>!m.attendance&&!m.attendees));
 await rpc(1,'onboarding_save',['build_week',1,'completed',4]);await assert.rejects(rpc(4,'onboarding_save',['build_week',1,'completed',4]),/unavailable/);await assert.rejects(f.as(4,'select * from private.staff_meeting_attendance'),/permission denied/);await f.db.exec('set role anon');await assert.rejects(f.db.query('select favorites_read()'),/permission denied/);await f.db.exec('reset role');
 }finally{await f.db.close()}});
