import {EmployeeImport} from './EmployeeImport';
import {useState} from 'react';
import type {Data,Profile} from './domain';
import {supabase} from './client';
type Props={data:Data;preview:boolean;isAdmin:boolean;reload:()=>Promise<void>;compact?:boolean};
export function AdminPanel({data,preview,reload,isAdmin,compact=false}:Props){
 const [search,setSearch]=useState('');
 const [section,setSection]=useState<'accounts'|'import'>('accounts'),[editing,setEditing]=useState<Profile|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[itTarget,setItTarget]=useState<Profile|null>(null);
 async function run(action:()=>Promise<string>){setError('');setMessage('');if(preview){setMessage('Disconnected preview: no account, email, or employee changes were made.');return}setBusy(true);try{setMessage(await action());await reload()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function accountAction(body:Record<string,unknown>){if(!supabase)throw Error('Connect Supabase first.');const result=await supabase.functions.invoke('manage-accounts',{body});if(result.error){const context=result.error.context;let detail='';if(context instanceof Response){try{detail=(await context.json()).error||''}catch{/* retain friendly fallback */}}throw Error(detail||'Account service unavailable. Confirm the manage-accounts function is installed and email delivery is configured.')}if(result.data?.error)throw Error(result.data.error);return result.data.message as string;}
 return <div className="admin-space">{!compact&&<div className="actions admin-tabs"><button className={section==='accounts'?'primary':''} onClick={()=>setSection('accounts')}>SHL accounts</button>{isAdmin&&<button className={section==='import'?'primary':''} onClick={()=>setSection('import')}>Import employees</button>}</div>}
 {error&&<p className="error" role="alert">{error}</p>}{message&&<p className="success" role="status">{message}</p>}
 {section==='accounts'||!isAdmin?<>{!compact&&<section className="panel admin-intro"><h2>Employee and manager logins</h2><p>Create a username and temporary password without email. GM and IT can also change usernames and reset passwords from the account screen.</p><a className="download-link" href="?workspace=manager&page=accounts">Create or manage username accounts</a></section>}
 <section className="panel"><div className="section-title"><h2>SHL access</h2></div>{data.profiles.length>1&&<label>Find an SHL<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search SHL name"/></label>}{data.profiles.filter(p=>p.name.toLowerCase().includes(search.toLowerCase())).map(p=><div className="person-row" key={p.id}><div className="grow"><strong>{p.name}</strong><small>{p.active?'Active':'Inactive'} · SHL{p.is_gm?' · GM':''}{p.is_admin?' · IT Admin':''}</small></div><button disabled={busy||(!p.active&&!p.is_admin)} onClick={()=>{setItTarget(p);setError('');setMessage('')}}>{p.is_admin?'Remove IT access':'Grant IT access'}</button>{isAdmin&&<><button disabled={busy} onClick={()=>{setEditing(p);setError('');setMessage('')}}>Edit access</button></>}</div>)}</section>
 {itTarget&&<section className="panel admin-intro" aria-label="Confirm IT access change"><h2>{itTarget.is_admin?'Remove':'Grant'} IT access: {itTarget.name}</h2><p>{itTarget.is_admin?'This removes IT administration privileges. The account keeps its existing manager and GM roles.':'This grants access to manage accounts, staff, and training jobs.'}</p><p className="muted">IT Admins and the GM can change IT access. At least one active IT Admin must remain.</p><div className="actions"><button disabled={busy} onClick={()=>setItTarget(null)}>Cancel</button><button className="primary" disabled={busy} onClick={()=>void run(async()=>{const {error}=await supabase!.rpc('set_it_access',{p_id:itTarget.id,p_admin:!itTarget.is_admin,p_version:itTarget.version});if(error)throw error;setItTarget(null);return 'IT access updated.'})}>{busy?'Saving…':itTarget.is_admin?'Confirm removal of IT access':'Confirm IT access'}</button></div></section>}
 {editing&&isAdmin&&<section className="panel admin-intro" aria-label="Edit manager access"><h2>Edit {editing.name}</h2><form key={editing.id+':'+editing.version} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(f.has('gm')&&!editing.is_gm&&!confirm('Transfer the GM designation to this manager?'))return;void run(async()=>{const {error}=await supabase!.rpc('admin_update_manager',{p_id:editing.id,p_name:f.get('name'),p_active:f.has('active'),p_admin:editing.is_admin,p_gm:f.has('gm'),p_version:editing.version});if(error)throw error;setEditing(null);return 'Account access updated.'})}}><label>Full name<input name="name" required maxLength={120} defaultValue={editing.name} disabled={busy}/></label><label className="check"><input name="active" type="checkbox" defaultChecked={editing.active} disabled={busy}/>Active account</label><p className="muted">Use Grant / Remove IT access above to change IT privileges.</p><label className="check"><input name="gm" type="checkbox" defaultChecked={editing.is_gm} disabled={busy}/>General manager (one active GM)</label><p className="muted">Deactivation removes workspace access immediately at the database. Records remain. Assign a replacement before deactivating the current GM. Use the separate IT access controls for promotions and demotions.</p><div className="actions"><button type="button" disabled={busy} onClick={()=>setEditing(null)}>Cancel</button><button className="primary" disabled={busy}>Save access</button></div></form></section>}</>:
 <EmployeeImport data={data} preview={preview} reload={reload}/>}</div>
}
