import {positionName} from './domain';
import {useState} from 'react';
import type {Data,Profile} from './domain';
import {supabase} from './client';
import {parseEmployees,personKey,type ImportRow} from './importCsv';
type Props={data:Data;preview:boolean;reload:()=>Promise<void>};
export function AdminPanel({data,preview,reload}:Props){
 const [section,setSection]=useState<'accounts'|'import'>('accounts'),[editing,setEditing]=useState<Profile|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [rows,setRows]=useState<ImportRow[]>([]),[batch,setBatch]=useState(''),[fileName,setFileName]=useState(''),[imported,setImported]=useState(false);
 const seen=new Set(data.staff.map(personKey));const review=rows.map(r=>{const duplicate=seen.has(personKey(r));seen.add(personKey(r));return {...r,duplicate}});
 const count=review.filter(r=>!r.duplicate).length;
 async function run(action:()=>Promise<string>){setError('');setMessage('');if(preview){setMessage('Disconnected preview: no account, email, or employee changes were made.');return}setBusy(true);try{setMessage(await action());await reload()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function accountAction(body:Record<string,unknown>){if(!supabase)throw Error('Connect Supabase first.');const result=await supabase.functions.invoke('manage-accounts',{body});if(result.error){const context=result.error.context;let detail='';if(context instanceof Response){try{detail=(await context.json()).error||''}catch{/* retain friendly fallback */}}throw Error(detail||'Account service unavailable. Confirm the manage-accounts function is installed and email delivery is configured.')}if(result.data?.error)throw Error(result.data.error);return result.data.message as string;}
 async function choose(file?:File){setRows([]);setImported(false);setError('');setMessage('');setFileName(file?.name||'');if(!file)return;if(file.size>1_000_000){setError('Choose a CSV smaller than 1 MB.');return}try{setRows(parseEmployees(await file.text()));setBatch(crypto.randomUUID())}catch(e){setError((e as Error).message)}}
 return <div className="admin-space"><div className="actions admin-tabs"><button className={section==='accounts'?'primary':''} onClick={()=>setSection('accounts')}>SHL accounts</button><button className={section==='import'?'primary':''} onClick={()=>setSection('import')}>Import employees</button></div>
 {error&&<p className="error" role="alert">{error}</p>}{message&&<p className="success" role="status">{message}</p>}
 {section==='accounts'?<><section className="panel admin-intro"><h2>Invite an SHL (manager)</h2><p className="muted">SHLs accept their email invitation once and set a password. After that, they can sign in with email and password. IT Admin controls accounts and the staff roster; GM is a separate designation. Every active manager can read meetings and notes. Editing stays with the creator.</p><form onSubmit={e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form);void run(async()=>{const msg=await accountAction({action:'invite',name:f.get('name'),email:f.get('email'),is_admin:f.has('admin')});form.reset();return msg})}}><div className="form-grid"><label>Full name<input name="name" required maxLength={120} disabled={busy}/></label><label>Email address<input name="email" type="email" required maxLength={254} disabled={busy}/></label></div><label className="check"><input type="checkbox" name="admin" disabled={busy}/>Also grant IT Admin access</label><button className="primary" disabled={busy}>{busy?'Working…':'Send invitation'}</button></form></section>
 <section className="panel"><div className="section-title"><h2>SHL access</h2></div>{data.profiles.map(p=><div className="person-row" key={p.id}><div className="grow"><strong>{p.name}</strong><small>{p.active?'Active':'Inactive'} · SHL{p.is_gm?' · GM':''}{p.is_admin?' · IT Admin':''}</small></div><button disabled={busy} onClick={()=>{setEditing(p);setError('');setMessage('')}}>Edit access</button><button disabled={busy||!p.active} onClick={()=>{if(confirm(`Send a new sign-in link to ${p.name}?`))void run(()=>accountAction({action:'send_link',id:p.id}))}}>Send sign-in link</button></div>)}</section>
 {editing&&<section className="panel admin-intro" aria-label="Edit manager access"><h2>Edit {editing.name}</h2><form key={editing.id+':'+editing.version} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(f.has('gm')&&!editing.is_gm&&!confirm('Transfer the GM designation to this manager?'))return;void run(async()=>{const {error}=await supabase!.rpc('admin_update_manager',{p_id:editing.id,p_name:f.get('name'),p_active:f.has('active'),p_admin:f.has('admin'),p_gm:f.has('gm'),p_version:editing.version});if(error)throw error;setEditing(null);return 'Account access updated.'})}}><label>Full name<input name="name" required maxLength={120} defaultValue={editing.name} disabled={busy}/></label><label className="check"><input name="active" type="checkbox" defaultChecked={editing.active} disabled={busy}/>Active account</label><label className="check"><input name="admin" type="checkbox" defaultChecked={editing.is_admin} disabled={busy}/>IT Admin</label><label className="check"><input name="gm" type="checkbox" defaultChecked={editing.is_gm} disabled={busy}/>General manager (one active GM)</label><p className="muted">Deactivation removes workspace access immediately at the database. Records remain. Assign a replacement before deactivating the current GM. Another IT Admin must remove your own administrator access.</p><div className="actions"><button type="button" disabled={busy} onClick={()=>setEditing(null)}>Cancel</button><button className="primary" disabled={busy}>Save access</button></div></form></section>}</>:
 <section className="panel admin-intro"><h2>Import your staff roster</h2><p className="muted">Upload up to 500 employees at once. Import FOH, HOH, or Catering employees here. Add SHLs through SHL accounts so they receive manager access. Existing names are skipped across all positions, including inactive staff. For two different people with the same full name, add the second person individually in Staff directory.</p><a className="download-link" download="employee-import-template.csv" href={'data:text/csv;charset=utf-8,'+encodeURIComponent('First Name,Last Name,Position,Active\nAlex,Example,FOH,Yes\nJordan,Example,HOH,Yes\nCasey,Example,Catering,Yes\n')}>Download CSV template</a><label>Employee CSV<input type="file" accept=".csv,text/csv" disabled={busy} onChange={e=>void choose(e.target.files?.[0])}/></label>
 {!!rows.length&&<><h3>Review: {fileName}</h3><p>{count} to add · {rows.length-count} duplicate names to skip</p><div className="import-table"><table><thead><tr><th>Name</th><th>Position</th><th>Active</th><th>Action</th></tr></thead><tbody>{review.map((r,i)=><tr key={i}><td>{r.first_name} {r.last_name}</td><td>{positionName(r.department)}</td><td>{r.active?'Yes':'No'}</td><td>{r.duplicate?'Skip existing name':'Add employee'}</td></tr>)}</tbody></table></div><p className="muted">Permanent IDs are assigned automatically. Existing records are never renamed, transferred, or overwritten by an import.</p><button className="primary" disabled={busy||!count||imported} onClick={()=>void run(async()=>{const {data:result,error}=await supabase!.rpc('admin_import_staff',{p_batch:batch,p_rows:rows});if(error)throw error;setImported(true);return `Import complete: ${result.added} added, ${result.skipped} skipped.`})}>{busy?'Importing…':imported?'Import complete':`Import ${count} employees`}</button></>}
 </section>}</div>
}
