import {useState} from 'react';
import {type SchedulerData,type Act,type Announcement} from './scheduler';
import {positionName,displayTime} from './domain';
import {Modal} from './SchedulerForms';
export function Announcements({data,act,busy}:{data:SchedulerData;act:Act;busy:boolean}){
 const [editing,setEditing]=useState<Announcement|null|undefined>(undefined),[error,setError]=useState('');const canPost=data.self.is_manager||data.self.is_ca;
 async function run(action:string,p:Record<string,unknown>){setError('');try{await act(action,p);setEditing(undefined)}catch(e){setError((e as Error).message)}}
 return <><section className="panel announcements"><div className="section-title"><div><h2>Announcements</h2><p className="muted">Updates for your team, right here in the app.</p></div>{canPost&&<button className="primary" onClick={()=>{setEditing(null);setError('')}}>New announcement</button>}</div>{error&&editing===undefined&&<p className="error">{error}</p>}{data.announcements.map(a=><article className="announcement" key={a.id}><div className="section-title"><h3>{a.title}</h3><span className={'chip '+(!a.read&&a.active?'orange':'')}>{!a.active?'Archived':a.read?'Read':'Unread'}</span></div><p className="muted">{a.author} · {displayTime(a.created_at)} · {a.groups.length?a.groups.map(positionName).join(', '):'Everyone'}</p><p className="announcement-body">{a.body}</p><div className="actions">{a.active&&!a.read&&<button disabled={busy} onClick={()=>void run('read',{announcement_id:a.id})}>Mark read</button>}{a.created_by===data.self.id&&canPost&&<button disabled={busy} onClick={()=>{setEditing(a);setError('')}}>Edit announcement</button>}</div>{a.created_by===data.self.id&&<details><summary>Revision history</summary>{data.announcement_history?.filter(h=>h.announcement_id===a.id).map(h=><div className="note" key={h.id}><small>{displayTime(h.at)} · {h.value.active?'Published':'Archived'}</small><h4>{h.value.title}</h4><p className="announcement-body">{h.value.body}</p></div>)}</details>}</article>)}{!data.announcements.length&&<div className="empty">No announcements yet.</div>}</section><section className="panel announcements"><div className="section-title"><h2>Your inbox</h2><button disabled={busy} onClick={()=>void run('read',{})}>Mark all read</button></div>{data.notifications.map(n=><article className={'notification '+(!n.read_at?'unread':'')} key={n.id}><p>{n.body}</p><small>{displayTime(n.created_at)}</small>{!n.read_at&&<button disabled={busy} onClick={()=>void run('read',{id:n.id})}>Mark read</button>}</article>)}{!data.notifications.length&&<div className="empty">You’re caught up.</div>}</section>
 {editing!==undefined&&<Modal title={editing?'Edit announcement':'New announcement'} busy={busy} onClose={()=>setEditing(undefined)}><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run('announcement',{...(editing?{id:editing.id,version:editing.version}:{}),title:f.get('title'),body:f.get('body'),groups:f.getAll('groups'),active:f.has('active')})}}><fieldset disabled={busy}><label>Title<input name="title" required maxLength={160} defaultValue={editing?.title}/></label><label>Message<textarea name="body" required maxLength={10000} rows={8} defaultValue={editing?.body}/></label><p>Select position groups, or leave all unchecked for everyone.</p><div className="actions">{['FOH','BOH','Catering','SHL'].map(g=><label className="check" key={g}><input name="groups" type="checkbox" value={g} defaultChecked={editing?.groups.includes(g)}/>{positionName(g)}</label>)}</div><label className="check"><input type="checkbox" name="active" defaultChecked={editing?.active??true}/>Published announcement</label><p className="muted">Changing an announcement marks the new version unread for its audience. Unchecking Published archives it.</p>{error&&<p role="alert" className="error">{error}</p>}<button className="primary" disabled={busy}>{busy?'Saving…':'Save announcement'}</button></fieldset></form></Modal>}</>
}
