import {useState} from 'react';
import {Modal} from './SchedulerForms';
import {bulkShiftChanges,linkedShiftIds} from './workflowSchedule';
import {addDays,clockTime,shiftDay,shiftLabel,type SchedulerData,type WorkShift,type Act} from './scheduler';
export function BulkShifts({data,act,busy,close,onIssues}:{data:SchedulerData;act:Act;busy:boolean;close:()=>void;onIssues:(issues:string[])=>void}){
 const [base]=useState(()=>data.week.draft!),[ids,setIds]=useState<string[]>([]),[operation,setOperation]=useState('move'),[minutes,setMinutes]=useState(30),[person,setPerson]=useState(''),[result,setResult]=useState<WorkShift[]|null>(null),[error,setError]=useState('');const linked=linkedShiftIds(data),stale=base.id!==data.week.draft?.id||base.version!==data.week.draft?.version;
 const describe=(s:WorkShift)=>`${data.people.find(p=>p.id===s.person_id)?.name||'Former teammate'} · ${shiftDay(s.start)} ${clockTime(s.start)}–${clockTime(s.end)} · ${shiftLabel(s,data.jobs)}`;
 return <Modal title="Bulk edit draft shifts" busy={busy} onClose={close}><form onSubmit={e=>{e.preventDefault();setError('');try{const next=bulkShiftChanges(base.shifts,ids,operation,minutes,person);if(next.some(s=>shiftDay(s.start)<data.week.start||shiftDay(s.start)>=addDays(data.week.start,7)))throw Error('Keep shift start dates within this week.');setResult(next)}catch(e){setError((e as Error).message)}}}><fieldset disabled={busy||stale}><p>Changes affect this private draft. Employees continue to see the published schedule until release.</p>{!result?<><p>Linked training, 1:1s and staff-meeting blocks must be changed through their own forms.</p><div className="workflow-list">{base.shifts.map(s=><label key={s.id}><input type="checkbox" name={s.id} disabled={linked.has(s.id)} checked={ids.includes(s.id)} onChange={e=>setIds(e.target.checked?[...ids,s.id]:ids.filter(id=>id!==s.id))}/>{describe(s)}{linked.has(s.id)?' · Linked activity':''}</label>)}</div><label>Change<select name="operation" value={operation} onChange={e=>setOperation(e.target.value)}><option value="move">Move start and end times</option><option value="assign">Reassign to one person</option><option value="remove">Remove selected shifts</option></select></label>{operation==='move'&&<label>Minutes earlier (−) or later (+)<input name="minutes" type="number" min={-720} max={720} step={1} value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></label>}{operation==='assign'&&<label>Team member<select name="person" value={person} onChange={e=>setPerson(e.target.value)} required><option value="">Choose a person</option>{data.people.filter(p=>p.active&&p.on_roster).map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label>}<button className="primary" disabled={!ids.length}>Review {ids.length} changes</button></>:<><h3>Review before saving</h3>{base.shifts.filter(s=>ids.includes(s.id)).map(s=><div className="workflow-change" key={s.id}><p>Before: {describe(s)}</p><p>After: {result.some(r=>r.id===s.id)?describe(result.find(r=>r.id===s.id)!):'Removed from draft'}</p></div>)}<p>Saving rechecks the draft. Resolve any conflicts and qualification warnings before release.</p><button type="button" onClick={()=>setResult(null)}>Back to selection</button><button className="primary" type="button" onClick={()=>{setError('');void act('save',{id:base.id,version:base.version,shifts:result}).then(r=>{onIssues((r.issues as string[])||[]);close()}).catch(e=>setError(e.message))}}>{busy?'Saving…':'Save reviewed changes to draft'}</button></>}</fieldset>{stale&&<p className="error" role="alert">The draft changed. Close and reopen bulk edit before saving.</p>}{error&&<p className="error" role="alert">{error} Your selection is retained.</p>}</form></Modal>
}
