import {useEffect,useState} from 'react';
import {supabase} from './client';
import {Modal} from './SchedulerForms';
import {addDays,clockTime,shiftDay,shiftLabel,type SchedulerData,type WorkShift,type Act} from './scheduler';
import {moveShiftDays} from './workflowSchedule';
export function CopyWeek({data,week,preview,busy,act,close}:{data:SchedulerData;week:string;preview:boolean;busy:boolean;act:Act;close:()=>void}){
 const [source,setSource]=useState(addDays(week,-7)),[sourceId,setSourceId]=useState<string|null>(null),[shifts,setShifts]=useState<WorkShift[]>([]),[selected,setSelected]=useState<string[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let live=true;setLoading(true);setError('');setShifts([]);setSelected([]);setSourceId(null);if(preview){const rows=(data.published.find(p=>p.week===week)?.shifts||[]).filter(s=>s.assignment_type!=='training').map(s=>moveShiftDays(s,-7));setShifts(rows);setSelected(rows.map(s=>s.id));setSourceId('demo-published');setLoading(false);return}void supabase!.rpc('copy_week_read',{p_week:source}).then(r=>{if(!live)return;setLoading(false);if(r.error)setError(r.error.message);else{setShifts(r.data.shifts);setSelected(r.data.shifts.map((s:WorkShift)=>s.id));setSourceId(r.data.revision)}});return()=>{live=false}},[source]);
 return <Modal title="Copy a previous week" busy={busy} onClose={close}><p>Copy selected published work shifts into a new private draft for {week}. Existing published shifts in the destination remain visible until release. The new draft replaces their proposed assignments.</p><p>Meetings, dedicated training, coaching links, 1:1s and release acknowledgments are not copied. Replan these for the new dates.</p><label>Source week (Sunday)<input type="date" value={source} disabled={preview||busy} onChange={e=>setSource(e.target.value)}/></label>{loading?<p role="status">Loading source schedule…</p>:<><div className="actions"><button disabled={busy} onClick={()=>setSelected(shifts.map(s=>s.id))}>Select all</button><button disabled={busy} onClick={()=>setSelected([])}>Clear selection</button></div><div className="workflow-list">{shifts.map(s=><label key={s.id}><input type="checkbox" disabled={busy} checked={selected.includes(s.id)} onChange={e=>setSelected(e.target.checked?[...selected,s.id]:selected.filter(id=>id!==s.id))}/>{data.people.find(p=>p.id===s.person_id)?.name||'Former teammate'} · {shiftDay(s.start)} · {clockTime(s.start)}–{clockTime(s.end)} · {shiftLabel(s,data.jobs)}</label>)}{!shifts.length&&<p>No eligible published work shifts in this week.</p>}</div></>}{error&&<p role="alert" className="error">{error}</p>}<p>Availability, qualifications, hours and overlapping assignments must be reviewed for the new dates. Save results and the release review show conflicts.</p><button className="primary" disabled={busy||loading||!sourceId||!selected.length} onClick={()=>{setError('');void act('copy_week',{source_week:source,source_revision:sourceId,week,ids:selected,...(preview?{shifts:shifts.filter(s=>selected.includes(s.id)).map(s=>({...moveShiftDays(s,7),id:crypto.randomUUID(),qualification_reason:''}))}:{})}).then(close).catch(e=>setError(e.message))}}>{busy?'Copying…':`Create draft with ${selected.length} ${selected.length===1?'shift':'shifts'}`}</button></Modal>
}
