import {useEffect,useState} from 'react';
import {supabase} from './client';
import type {SchedulerData,WorkShift} from './scheduler';
import {hoursLabel} from './Planning';
import {linkedShiftIds} from './workflowSchedule';
type Candidate={id:string;reasons:string[];warning?:string;hours:number|null};
export function CoveragePicker({data,shift,preview,onChoose}:{data:SchedulerData;shift:WorkShift;preview:boolean;onChoose:(id:string)=>void}){
 const [rows,setRows]=useState<Candidate[]|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0),[search,setSearch]=useState('');const locked=linkedShiftIds(data).has(shift.id);
 useEffect(()=>{let live=true;setRows(null);setError('');if(preview){setError('Live eligibility checks are unavailable in disconnected preview.');return}if(locked)return;void supabase!.rpc('assignment_candidates',{p_week:data.week.start,p_revision:data.week.draft?.id||null,p_version:data.week.draft?.version||null,p_shift:shift}).then(r=>{if(live){if(r.error)setError(r.error.message);else setRows(r.data.candidates)}});return()=>{live=false}},[shift.id,data.week.draft?.version,retry,preview,locked]);
 const visible=(rows||[]).filter(c=>c.id!==shift.person_id&&data.people.find(p=>p.id===c.id)?.name.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>Number(!!(a.reasons.length||a.warning))-Number(!!(b.reasons.length||b.warning))||(a.hours??0)-(b.hours??0));
 return <section className="panel scheduler-card"><h3>Find coverage</h3>{locked?<p>Replan the linked training or meeting before changing this person’s assignment.</p>:<><p>Qualified, conflict-free candidates appear first, with projected hours after taking this shift. Choose a person, then save the shift to the private draft.</p><label>Search coverage candidates<input type="search" value={search} onChange={e=>setSearch(e.target.value)}/></label>{error?<p role="alert" className="error">Assessment unavailable: {error} <button type="button" onClick={()=>setRetry(n=>n+1)}>Retry checks</button></p>:!rows?<p role="status">Checking qualifications, availability and hours…</p>:<div className="workflow-list">{visible.map(c=><div className="workflow-change" key={c.id}><strong>{data.people.find(p=>p.id===c.id)?.name}</strong><p>{c.hours===null?'Salaried':hoursLabel(c.hours)+' projected this week'}{c.hours!==null&&c.hours>=35?' · Hours acknowledgment may be required':''}</p>{c.reasons.map(r=><p key={r}>{r}</p>)}{c.warning&&<p>{c.warning}</p>}<button type="button" disabled={!!(c.reasons.length||c.warning)} onClick={()=>onChoose(c.id)}>Choose {data.people.find(p=>p.id===c.id)?.name}</button></div>)}{!visible.length&&<p>No other candidates match this search.</p>}</div>}</>}</section>
}
