import {useEffect,useRef,useState} from 'react';
import {supabase} from './client';
import {addDays,type SchedulerData} from './scheduler';
type Band={min:number;max:number|null;jobs:Record<string,number>};
type Period={name:string;start:string;end:string;bands:Band[]};
type Day={dow:number;lunch_percent:number|null;periods:Period[]};
type Settings={rules:{version:number;days:Day[]};forecasts:{day:string;amount:number;version:number}[];periods:{day:string;lunch:number;dinner:number;version:number}[];overrides:{day:string;targets:{name:string;jobs:Record<string,number>}[];version:number;reason:string}[];can_configure:boolean};
const freshDay=(dow:number):Day=>({dow,lunch_percent:null,periods:[{name:'Lunch',start:'',end:'16:00',bands:[{min:0,max:null,jobs:{}}]},{name:'Dinner',start:'16:00',end:'',bands:[{min:0,max:null,jobs:{}}]}]});
export function CoverageSettings({week,data,onSaved,preview=false}:{week:string;data:SchedulerData;onSaved:()=>void;preview?:boolean}){
 const [settings,setSettings]=useState<Settings|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[day,setDay]=useState(0),[draft,setDraft]=useState<Day>(freshDay(0));const pending=useRef<{key:string;id:string}|null>(null);
 async function load(){const r=await supabase!.rpc('coverage_read',{p_week:week});if(r.error)throw r.error;setSettings(r.data);setDraft(r.data.rules.days.find((d:Day)=>d.dow===day)||freshDay(day))}
 useEffect(()=>{let active=true;setSettings(null);if(preview){setSettings({rules:{version:1,days:[]},forecasts:[],periods:[],overrides:[],can_configure:data.self.is_admin||!!data.self.is_gm});return;}void supabase?.rpc('coverage_read',{p_week:week}).then(r=>{if(active){setError(r.error?.message||'');setSettings(r.data);setDay(0);setDraft(r.data?.rules.days.find((d:Day)=>d.dow===0)||freshDay(0))}});return()=>{active=false}},[week,preview]);
 async function save(kind:string,payload:Record<string,unknown>){if(preview){setError('Visual preview only. No staffing rules or forecasts were saved.');return;}setBusy(true);setError('');try{const key=JSON.stringify([kind,payload]);if(pending.current?.key!==key)pending.current={key,id:crypto.randomUUID()};const r=await supabase!.rpc('coverage_save',{p_kind:kind,p_payload:payload,p_submission:pending.current.id});if(r.error)throw r.error;pending.current=null;await load();onSaved()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function editPeriod(index:number,p:Period){setDraft({...draft,periods:draft.periods.map((x,i)=>i===index?p:x)})}
 function jobs(values:Record<string,number>,change:(v:Record<string,number>)=>void){return <div className="coverage-job-inputs">{data.jobs.filter(j=>j.active).map(j=><label key={j.id}>{j.name}<input type="number" min="0" max="100" step="1" placeholder="Not targeted" value={values[j.id]??''} onChange={e=>{const v={...values};if(e.target.value==='')delete v[j.id];else v[j.id]=Number(e.target.value);change(v)}}/></label>)}</div>}
 return <details className="panel scheduler-card"><summary>Sales forecasts & staffing targets</summary>{error&&<p className="error" role="alert">{error}</p>}{!settings?<p>Loading staffing setup…</p>:<fieldset disabled={busy}><p>Staffing is recommended from sales bands. Blank job headcounts are not targeted; enter 0 to explicitly target no coverage. Save actual store settings before relying on recommendations.</p>{settings.can_configure&&<details><summary>GM/IT: configure weekday staffing</summary><label>Weekday<select value={day} onChange={e=>{const n=Number(e.target.value);setDay(n);setDraft(settings.rules.days.find(d=>d.dow===n)||freshDay(n))}}>{['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].map((n,i)=><option key={n} value={i}>{n}</option>)}</select></label><form onSubmit={e=>{e.preventDefault();void save('rules',{version:settings.rules.version,days:[...settings.rules.days.filter(d=>d.dow!==day),draft].sort((a,b)=>a.dow-b.dow)})}}><label>Default Lunch share of daily sales (%)<input type="number" min="0" max="100" step="0.01" required value={draft.lunch_percent??''} onChange={e=>setDraft({...draft,lunch_percent:e.target.value===''?null:Number(e.target.value)})}/></label>{draft.periods.map((p,i)=><section key={p.name}><h4>{p.name}</h4><div className="form-grid"><label>Start<input type="time" required value={p.start} readOnly={p.name==='Dinner'} onChange={e=>editPeriod(i,{...p,start:e.target.value})}/></label><label>End<input type="time" required value={p.end} readOnly={p.name==='Lunch'} onChange={e=>editPeriod(i,{...p,end:e.target.value})}/></label></div>{p.bands.map((b,k)=><div className="coverage-band" key={k}><div className="form-grid"><label>Sales from ($, included)<input type="number" min="0" step="0.01" required value={b.min} onChange={e=>editPeriod(i,{...p,bands:p.bands.map((x,n)=>n===k?{...x,min:Number(e.target.value)}:x)})}/></label><label>Sales below ($, blank means no limit)<input type="number" min="0" step="0.01" value={b.max??''} onChange={e=>editPeriod(i,{...p,bands:p.bands.map((x,n)=>n===k?{...x,max:e.target.value===''?null:Number(e.target.value)}:x)})}/></label></div>{jobs(b.jobs,v=>editPeriod(i,{...p,bands:p.bands.map((x,n)=>n===k?{...x,jobs:v}:x)}))}{p.bands.length>1&&<button type="button" onClick={()=>editPeriod(i,{...p,bands:p.bands.filter((_,n)=>n!==k)})}>Remove band</button>}</div>)}<button type="button" onClick={()=>editPeriod(i,{...p,bands:[...p.bands,{min:p.bands.at(-1)?.max||0,max:null,jobs:{}}]})}>Add sales band</button></section>)}<button className="primary">Save weekday rules</button></form></details>}{Array.from({length:7},(_,i)=>addDays(week,i)).map((date,i)=><ForecastDay key={date+JSON.stringify(settings)} date={date} settings={settings} weekday={settings.rules.days.find(d=>d.dow===i)} jobsEditor={jobs} save={save}/>)}</fieldset>}</details>
}
function ForecastDay({date,settings,weekday,jobsEditor,save}:{date:string;settings:Settings;weekday?:Day;jobsEditor:(v:Record<string,number>,change:(v:Record<string,number>)=>void)=>React.ReactNode;save:(kind:string,p:Record<string,unknown>)=>Promise<void>}){
 const f=settings.forecasts.find(f=>f.day===date),p=settings.periods.find(f=>f.day===date),o=settings.overrides.find(f=>f.day===date);
 const [total,setTotal]=useState(String(f?.amount??'')),[lunch,setLunch]=useState(String(p?.lunch??'')),[dinner,setDinner]=useState(String(p?.dinner??'')),[targets,setTargets]=useState(o?.targets||[{name:'Lunch',jobs:{}},{name:'Dinner',jobs:{}}]);
 return <details><summary>{date} · {f?'$'+f.amount:'Forecast needed'}{o?' · Target override':''}</summary><form onSubmit={e=>{e.preventDefault();void save('forecast',{day:date,total:Number(total),lunch:Number(lunch),dinner:Number(dinner),version:f?.version||0,period_version:p?.version||0})}}><label>Daily sales ($)<input type="number" min="0" step="0.01" required value={total} onChange={e=>setTotal(e.target.value)}/></label><button type="button" disabled={!weekday||total===''} onClick={()=>{const l=Math.round(Number(total)*Number(weekday!.lunch_percent))/100;setLunch(l.toFixed(2));setDinner((Number(total)-l).toFixed(2))}}>Apply configured Lunch/Dinner split</button><div className="form-grid"><label>Lunch sales ($)<input type="number" min="0" step="0.01" required value={lunch} onChange={e=>setLunch(e.target.value)}/></label><label>Dinner sales ($)<input type="number" min="0" step="0.01" required value={dinner} onChange={e=>setDinner(e.target.value)}/></label></div><button>Save sales forecast</button></form><details><summary>Override this date’s job targets</summary><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void save('override',{day:date,version:o?.version||0,targets,reason:f.get('reason'),remove:(e.nativeEvent as SubmitEvent).submitter?.getAttribute('value')==='remove'})}}>{targets.map((p,i)=><section key={p.name}><h4>{p.name}</h4>{jobsEditor(p.jobs,v=>setTargets(targets.map((t,k)=>k===i?{...t,jobs:v}:t)))}</section>)}<label>Reason<textarea name="reason" minLength={3} required defaultValue={o?.reason||''}/></label><button>Save target override</button>{o&&<button value="remove">Restore sales-based targets</button>}</form></details></details>
}
