import {useState,useRef} from 'react';
import {supabase} from './client';
import {today} from './domain';
import {downloadCsv} from './labor';
import {directoryCells,parseDirectory,type DirectoryRow} from './directoryCsvData';
type Review={fingerprint:string;rows:{row:number;changed:boolean;before:DirectoryRow;after:DirectoryRow&{qualifications_to_add:string[]}}[]};
export function DirectoryCsv({preview,onSaved}:{preview:boolean;onSaved:()=>Promise<void>}){
 const [busy,setBusy]=useState(false),[rows,setRows]=useState<DirectoryRow[]>([]),[review,setReview]=useState<Review|null>(null),[error,setError]=useState(''),[message,setMessage]=useState('');const batch=useRef('');
 async function download(){setBusy(true);setError('');try{if(preview)throw Error('Download requires a connected GM or IT account.');const r=await supabase!.rpc('directory_csv_export');if(r.error)throw r.error;downloadCsv('shift-employee-directory-'+today()+'.csv',directoryCells(r.data));}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function choose(file?:File){setReview(null);setRows([]);setError('');setMessage('');if(!file)return;try{if(file.size>1_000_000)throw Error('Choose a CSV smaller than 1 MB.');setRows(parseDirectory(await file.text()));batch.current=crypto.randomUUID()}catch(e){setError((e as Error).message)}}
 async function inspect(){setBusy(true);setError('');setReview(null);try{if(preview)throw Error('Review requires a connected GM or IT account.');const r=await supabase!.rpc('directory_csv_review',{p_rows:rows});if(r.error)throw r.error;setReview(r.data)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function save(){if(!review||!confirm('Save these reviewed employee changes? Newly listed earned jobs become prior-experience qualifications. Trainer roles are replaced by the reviewed list.'))return;setBusy(true);setError('');try{const r=await supabase!.rpc('directory_csv_apply',{p_rows:rows,p_fingerprint:review.fingerprint,p_submission:batch.current});if(r.error)throw r.error;setRows([]);setReview(null);setMessage(`${r.data.updated} employees updated; ${r.data.unchanged} unchanged.`);try{await onSaved()}catch{setMessage('Changes saved. Refresh the directory to see them.')}}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="panel scheduler-card"><h2>Edit employee directory by CSV</h2><p>GM and IT can update active employee records, including SHLs linked to an employee. Technical accounts without an employee record are managed under Accounts & access.</p><button disabled={busy} onClick={()=>void download()}>Download employee directory CSV</button><p>Keep Staff ID and Revision unchanged. Edit names, Primary Job, Earned Jobs, and Trainer Roles. Quote lists containing commas. Blank Primary Job keeps the current job. Earned Jobs adds qualifications; omitted jobs are not revoked. Trainer Roles replaces the list; blank removes configured trainer roles. Legacy trainers without configured roles stay unchanged.</p><p>Contacts, wages, account permissions, and removal are not changed. Download a fresh CSV if an employee has changed since export.</p><label>Upload edited directory CSV<input type="file" accept=".csv,text/csv" disabled={busy} onChange={e=>void choose(e.target.files?.[0])}/></label>{rows.length>0&&<button disabled={busy} onClick={()=>void inspect()}>Review {rows.length} employees</button>}{review&&<><h3>Review before saving</h3>{review.rows.map(r=><article className="note" key={r.before.staff_id}><strong>{r.before.first_name} {r.before.last_name} · {r.changed?'Update':'Unchanged'}</strong>{r.changed&&<><p>Name: {r.before.first_name} {r.before.last_name} → {r.after.first_name} {r.after.last_name}</p><p>Primary job: {r.before.primary_job||'None'} → {r.after.primary_job||'None'}</p><p>New earned jobs: {r.after.qualifications_to_add.join(', ')||'None'}</p><p>Trainer roles: {r.before.trainer_roles.join(', ')||'None'} → {r.after.trainer_roles.join(', ')||'None'}</p></>}</article>)}<button className="primary" disabled={busy||!review.rows.some(r=>r.changed)} onClick={()=>void save()}>Save reviewed changes</button></>}{error&&<p role="alert" className="error">{error}</p>}{message&&<p role="status" className="success">{message}</p>}</section>;
}
