import {useState} from 'react';
import {type Employee,positionName} from './domain';
import type {TrainingPosition,TrainingSignoff} from './trainingProgress';
export function EmployeeJobFields({employee,positions,signoffs}:{employee?:Employee;positions:TrainingPosition[];signoffs:TrainingSignoff[]}){
 const [primary,setPrimary]=useState(employee?.primary_job_id||'');
 const eligible=positions.filter(p=>p.active&&p.name!=='GM'&&(!employee||signoffs.some(s=>s.staff_id===employee.id&&s.training_position_id===p.id&&s.active)));
 const value=eligible.some(p=>p.id===primary)?primary:employee?.primary_job_id||'';
 const job=positions.find(p=>p.id===value),retained=!!value&&!eligible.some(p=>p.id===value);
 if(employee?.leadership_title)return <><label>Primary job<input value={employee.leadership_title} readOnly/></label><input type="hidden" name="primaryJob" value={employee.primary_job_id||''}/><input type="hidden" name="department" value="SHL"/><p className="muted">Managed by the {employee.leadership_title==='GM'?'GM account designation':'sSHL qualification'}. Individual shifts can still be assigned to operational jobs.</p></>;
 return <><label>{employee?'Primary job':'Initial training job'}<select required name="primaryJob" value={value} onChange={e=>setPrimary(e.target.value)}><option value="">{employee?'Choose a qualified primary job':'Choose an initial training job'}</option>{retained&&<option value={value} hidden disabled>{job?.name||'Current job'} · unchanged</option>}{['FOH','BOH','Catering','SHL'].map(group=>{const jobs=eligible.filter(p=>p.department===group);return jobs.length>0&&<optgroup label={positionName(group)} key={group}>{jobs.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</optgroup>})}</select></label><input type="hidden" name="department" value={job?.department||employee?.department||'FOH'}/>{employee?<><p className="muted">Only active jobs with recorded readiness sign-off or approved prior experience can be selected. Qualifications can span every position group.</p>{!eligible.length&&<p className="notice">No qualified jobs recorded yet. Complete training and confirm readiness, or have GM/IT record prior experience below.</p>}{retained&&<p className="muted">Existing primary job: {job?.name||'Former job'}. It is preserved until you select a qualified replacement; this does not grant a qualification.</p>}</>:<p className="muted">Choose where this new employee will begin training. This does not mark them qualified. After saving, record training or approved prior experience.</p>}<p className="muted">Primary group: {job?positionName(job.department):'Choose a job'}.</p></>;
}
