import {useState} from 'react';
import {supabase} from './client';
import {positionName,type Data,type Employee} from './domain';
import {trainingProgress} from './trainingProgress';
export function EmployeeQualifications({employee,data,canOverride,preview,reload,onTraining}:{employee:Employee;data:Data;canOverride:boolean;preview:boolean;reload:()=>Promise<void>;onTraining:(job:string)=>void}){
 const [pending,setPending]=useState<{job:string;action:string;version:number}|null>(null),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function apply(){if(!pending)return;setBusy(true);setError('');try{if(preview)throw Error('Disconnected demo: no qualification changes are saved.');const r=await supabase!.rpc('set_job_qualification',{p_staff:employee.id,p_job:pending.job,p_action:pending.action,p_reason:reason,p_version:pending.version,p_submission:crypto.randomUUID()});if(r.error)throw r.error;setPending(null);setReason('');await reload()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="employee-qualifications"><h3>Jobs & qualifications</h3>{['FOH','BOH','Catering','SHL'].map(group=><section key={group}><h4>{positionName(group)}</h4>{data.trainingPositions.filter(j=>j.department===group&&(j.active||data.trainingSignoffs.some(f=>f.staff_id===employee.id&&f.training_position_id===j.id&&f.active))).map(j=>{const progress=trainingProgress(employee.id,j,data.training),f=data.trainingSignoffs.find(f=>f.staff_id===employee.id&&f.training_position_id===j.id&&f.active);return <div className="qualification-row" key={j.id}><div><strong>{j.name}{employee.primary_job_id===j.id?' · Primary':''}</strong><small>{f?'Qualified'+(f.origin&&f.origin!=='training'?' · Prior experience':''):progress.started?'In training':'Not qualified'} · {progress.completed}/{progress.target} recorded shifts</small></div><div className="actions">{!f&&j.active&&<><button type="button" onClick={()=>onTraining(j.id)}>Schedule training</button>{!progress.remaining&&(group!=='SHL'||canOverride)&&<button type="button" disabled={busy} onClick={()=>setPending({job:j.id,action:'signoff',version:0})}>Confirm readiness</button>}{canOverride&&<button type="button" disabled={busy} onClick={()=>{setReason('');setPending({job:j.id,action:'override',version:0})}}>Qualify now</button>}</>}{f&&canOverride&&<button type="button" disabled={busy} onClick={()=>{setReason('');setPending({job:j.id,action:'revoke',version:f.version})}}>Revoke qualification</button>}</div></div>})}</section>)}{pending&&<div className="notice"><strong>{pending.action==='revoke'?'Revoke qualification':pending.action==='override'?'Confirm prior experience':'Confirm readiness'} · {data.trainingPositions.find(j=>j.id===pending.job)?.name}</strong><p>Training history will remain unchanged. hSHL permits office shifts; sSHL also enables Manager View and schedule management for a linked active account. GM/IT access is preserved.</p>{pending.action!=='signoff'&&<label>Reason<textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={2000}/></label>}<div className="actions"><button type="button" disabled={busy} onClick={()=>setPending(null)}>Cancel</button><button type="button" disabled={busy||(pending.action!=='signoff'&&!reason.trim())} onClick={()=>void apply()}>Confirm qualification change</button></div></div>}{error&&<p className="error" role="alert">{error}</p>}</section>
}
