export const guides=[
 {id:'schedule',title:'Build and release a schedule',page:'schedule',steps:['Choose the correct week and create or open its draft.','Use Add shift under a day. Select the person, assignment, times and any shared shift notes.','Review the complete release. Resolve conflicts and acknowledge hours and coverage warnings with a reason.','Release now or choose a release time. Cancel a queued release before editing.'],keywords:'draft publish unlock overtime 35 40',recovery:'If the draft changed, refresh and review again. A draft is private until release.'},
 {id:'coverage',title:'Set up coverage and hours planning',page:'settings',restricted:true,steps:['Open Scheduling configuration.','Enter actual service windows, sales splits and staffing bands.','Save the configuration and review the affected schedule again.'],keywords:'sales forecast staffing shortage overtime labor',recovery:'Missing setup means coverage is unknown. Position filters do not exclude hours in other jobs.'},
 {id:'requests',title:'Review availability, time off and shift trades',page:'requests',steps:['Open the specific request in Approvals.','Check the employee, dates and proposed changes. Trades require coworker acceptance before manager approval.','Review conflicts and the hours/coverage assessment, then approve or deny. Explain a denial.'],keywords:'PTO RTO trade cover offer approve deny',recovery:'Current approved restrictions remain until the replacement is approved. Resolve conflicts before trying again.'},
 {id:'directory',title:'Find and update a teammate',page:'directory',steps:['Search Staff directory and open the person’s profile.','Choose the relevant profile section or Edit details.','Check the changes and save.'],keywords:'employee name primary job trainer qualifications import export CSV',recovery:'Check inactive filters and the selected store if a person is missing. Similar names do not necessarily identify the same person.'},
 {id:'training',title:'Manage qualifications and training',page:'training',steps:['Find the person and job in Training.','Schedule training alongside an eligible trainer on a work shift.','Record the outcome after the session. Confirm readiness when the target is reached.'],keywords:'fully trained signoff completed four shifts revoke recertification',recovery:'GM/IT can record prior experience with a reason. Dedicated Training blocks do not create position-training credits.'},
 {id:'meetings',title:'Choose a staff meeting or a 1:1',page:'staffMeetings',steps:['Use Staff meetings for a group such as trainers or everyone qualified for a job.','Choose a separate Training block or a period within existing work.','For a private employee–manager check-in, open 1:1s instead.'],keywords:'group trainers recertification',recovery:'Staff meetings count as Training and do not reset the six-month 1:1 clock.'},
 {id:'oneOnOnes',title:'Arrange and complete a 1:1',page:'oneOnOnes',steps:['Open 1:1s and choose the employee needing a check-in.','Select an eligible employee shift and manager with overlapping work.','After the conversation, its creator marks it completed with the actual completion date.'],keywords:'meeting six months priority notes manager',recovery:'Only the creator can edit the booking. Scheduling alone does not clear the underlying due status.'},
 {id:'accounts',title:'Create accounts and manage access',page:'accounts',steps:['Add a new teammate in Staff directory if needed.','Open Accounts & access or the person’s account section.','Use the authorized account creation, access or reset control and check its confirmation.'],keywords:'username password login disabled GM IT sSHL hSHL',recovery:'An account can be disabled while its employee history remains. hSHL alone does not grant schedule management.'},
 {id:'csv',title:'Download or update the directory using CSV',page:'directory',restricted:true,steps:['Open Import / export in Staff directory.','Download the current directory and keep its identifiers and revision fields.','Upload the edited file, inspect the review, and apply the approved changes.'],keywords:'import export migration spreadsheet',recovery:'Refresh the export if a record changed. Do not repeatedly submit after a successful save followed by a refresh error.'},
 {id:'calendar',title:'Calendar subscriptions and phone installation',page:'profile',steps:['Use Employee View → More → My profile & calendar for your personal calendar subscription.','Keep your calendar link private. Calendar apps may take time to refresh.','Use the Install app instructions for a phone home-screen shortcut.'],keywords:'iOS Android Apple Google calendar install phone',recovery:'Calendar feeds show released information. Contact your store’s IT administrator if your account has no roster link.'},
 {id:'troubleshooting',title:'Missing information or a failed save',page:'home',steps:['Check your store, date, filters and whether the record is published.','Read the error before retrying. Save or discard unsaved edits before refreshing.','If saving succeeded but refresh failed, refresh the page rather than submitting again.'],keywords:'error connection stale missing permissions unavailable',recovery:'Contact your store’s IT administrator with the page and error message. Do not send passwords or private calendar links.'}
];

export const employeeGuides:typeof guides=[
 {id:'schedule',title:'Find your schedule and shift details',page:'schedule',steps:['Open My Schedule and choose the week.','Read the published card for your job, times, shift notes, training and 1:1 details.','If the week is missing, contact your manager; drafts are private until release.'],keywords:'work shift time meeting training',recovery:'Check the selected week and account. Refresh if your manager has just released changes.'},
 {id:'requests',title:'Time off, trades and coverage',page:'requests',steps:['Use Requests for time off. Use an eligible upcoming schedule card to trade, ask a coworker to cover, or offer a shift.','For shift changes, wait for coworker acceptance or a claim, then manager approval.','Check the final outcome before treating your schedule as changed.'],keywords:'PTO RTO trade offer cover approve',recovery:'Linked training or meetings may require your manager to replan the shift. Started or cancelled shifts cannot be traded.'},
 {id:'availability',title:'Update availability',page:'availability',steps:['Open My availability.','Enter the days and times you can work and the effective date.','Submit for review. Existing approved availability remains until the change is approved.'],keywords:'hours days available restrictions',recovery:'Contact your manager if approved shifts conflict with the proposed change.'},
 {id:'training',title:'Training and qualifications',page:'training',steps:['Open Training from More.','Check your upcoming training and progress.','Ask an authorized manager about completion or prior-experience sign-off.'],keywords:'trained qualification progress',recovery:'A scheduled training session is not completed credit until the outcome is recorded.'},
 {id:'calendar',title:'Calendar and installing STARS-S',page:'profile',steps:['Open My profile & calendar from More for your personal subscription.','Keep your calendar link private.','Use Add STARS-S to your phone for home-screen installation instructions.'],keywords:'phone iOS Android install calendar',recovery:'Calendar apps may take time to refresh. The in-app published schedule is the current STARS record.'},
 {id:'troubleshooting',title:'Missing information or connection problems',page:'home',steps:['Check your week and signed-in account.','Refresh if a record has recently changed.','Contact your store IT administrator for account help; never send passwords or calendar links.'],keywords:'help error password account missing',recovery:'If a save succeeded but refresh failed, refresh instead of submitting the same request again.'}
];
