import {createPortal} from 'react-dom';
import {useEffect,useId,useRef,useState} from 'react';
import {supabase} from './client';
import {managementGroups} from './workspaces';
function Group({label,active,children}:{label:string;active:boolean;children:React.ReactNode}){const [open,setOpen]=useState(active||label==='Favorites'),id=useId();useEffect(()=>{if(active)setOpen(true)},[active]);return <section className="nav-group"><h2><button className="nav-group-toggle" aria-expanded={open} aria-controls={id} onClick={()=>setOpen(!open)}>{label}<span aria-hidden="true">{open?'▾':'▸'}</span></button></h2><div id={id} className="nav-group-links" hidden={!open}>{children}</div></section>}
const demoFavorites=new Map<string,string[]>();
export function ManagementNavigation({userId,admin,view,unread,go,preview}:{userId:string;admin:boolean;view:string;unread:number;go:(id:string)=>void;preview:boolean}){
 const [saved,setSaved]=useState<{version:number;pages:string[]}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const attempt=useRef<{key:string;id:string}|null>(null);
 async function load(){setError('');if(preview){setSaved({version:0,pages:demoFavorites.get(userId)||[]});return}const r=await supabase!.rpc('favorites_read');if(r.error)setError('Favorites unavailable. Retry to load them.');else setSaved(r.data)}
 useEffect(()=>{setSaved(null);void load()},[userId,preview]);
 const groups=managementGroups.map(([label,items])=>[label,items.filter(([id])=>id!=='audit'||admin)] as [string,[string,string][]]);const allowed=groups.flatMap(([,items])=>items);
 async function toggle(id:string){if(!saved||busy)return;const pages=saved.pages.includes(id)?saved.pages.filter(p=>p!==id):[...saved.pages,id];setBusy(true);setError('');try{if(preview){demoFavorites.set(userId,pages);setSaved({version:0,pages});return}const key=JSON.stringify([saved.version,pages]);if(attempt.current?.key!==key)attempt.current={key,id:crypto.randomUUID()};const r=await supabase!.rpc('favorites_save',{p_version:saved.version,p_pages:pages,p_submission:attempt.current.id});if(r.error)throw r.error;setSaved(r.data);attempt.current=null}catch(e){setError((e as Error).message+' Retry loading before another change.')}finally{setBusy(false)}}
 const link=([id,title]:[string,string])=><button key={id} data-tour-nav={id} className={view===id?'selected':''} aria-current={view===id?'page':undefined} onClick={()=>go(id)}>{title}{id==='announcements'&&unread>0&&<span className="nav-count">{unread}</span>}</button>;
 const titleTarget=document.getElementById('page-favorite-control'),current=allowed.find(([id])=>id===view),pinned=!!saved?.pages.includes(view);

 return <>{titleTarget&&current&&createPortal(<button className="page-favorite-toggle" disabled={!saved||busy} aria-pressed={pinned} aria-label={(pinned?'Unpin ':'Pin ')+current[1]} title={(pinned?'Remove from':'Add to')+' Favorites'} onClick={()=>void toggle(view)}><span aria-hidden="true">{pinned?'★':'☆'}</span></button>,titleTarget)}<Group label="Favorites" active={!!saved?.pages.includes(view)}>{!saved&&!error?<p role="status">Loading favorites…</p>:saved?.pages.filter(id=>allowed.some(p=>p[0]===id)).length?saved.pages.flatMap(id=>{const p=allowed.find(p=>p[0]===id);return p?[link(p)]:[]}):<p>Use the star beside a page title to add it here.</p>}{error&&<p role="alert">{error}<button disabled={busy} onClick={()=>void load()}>Retry</button></p>}</Group>{groups.map(([label,items])=>label?<Group key={label} label={label} active={items.some(([id])=>id===view)}>{items.map(link)}</Group>:<section className="nav-group" key="help">{items.map(link)}</section>)}</>;
}
