import {useState} from 'react';
import {ChevronLeft,ChevronRight,Plus} from 'lucide-react';
import {type Data,type Meeting,type Employee,labels,today,zone} from './domain';
export function MeetingCalendar({data,onMeeting,onSchedule}:{data:Data;onMeeting:(m:Meeting)=>void;onSchedule:(p?:Employee,date?:string)=>void}){
 const [month,setMonth]=useState(today().slice(0,7)),[layout,setLayout]=useState<'calendar'|'agenda'>('calendar'),[search,setSearch]=useState(''),[department,setDepartment]=useState(''),[status,setStatus]=useState('Scheduled');
 const [year,mon]=month.split('-').map(Number),first=new Date(Date.UTC(year,mon-1,1));
 const count=new Date(Date.UTC(year,mon,0)).getUTCDate(),offset=first.getUTCDay(),length=Math.ceil((offset+count)/7)*7;
 const name=(id:string)=>{const p=data.staff.find(p=>p.id===id);return p?`${p.first_name} ${p.last_name}`:'Unknown employee'};
 const manager=(id:string)=>data.profiles.find(p=>p.id===id)?.name||'Former manager';
 const dayOf=(m:Meeting)=>new Intl.DateTimeFormat('sv-SE',{timeZone:zone}).format(new Date(m.scheduled_at));
 const time=(m:Meeting)=>new Intl.DateTimeFormat('en-US',{timeZone:zone,hour:'numeric',minute:'2-digit'}).format(new Date(m.scheduled_at));
 const matches=(p?:Employee)=>!department||p?.department===department;
 const meetings=data.meetings.filter(m=>(status==='All'||m.status===status)&&matches(data.staff.find(p=>p.id===m.staff_id))&&(name(m.staff_id)+' '+manager(m.manager_id)).toLowerCase().includes(search.toLowerCase())).sort((a,b)=>a.scheduled_at.localeCompare(b.scheduled_at));
 const visible=meetings.filter(m=>dayOf(m).startsWith(month));
 const attention=data.staff.filter(p=>p.active&&matches(p)&&name(p.id).toLowerCase().includes(search.toLowerCase())).filter(p=>{const l=labels(p,data);return l.needs||l.priority||l.requested}).sort((a,b)=>{const x=labels(a,data),y=labels(b,data);return Number(y.priority)-Number(x.priority)||Number(y.requested)-Number(x.requested)||(x.due||'').localeCompare(y.due||'')||name(a.id).localeCompare(name(b.id))});
 function changeMonth(n:number){const d=new Date(Date.UTC(year,mon-1+n,1));setMonth(d.toISOString().slice(0,7))}
 function event(m:Meeting){return <button key={m.id} className={'calendar-event status-'+m.status.toLowerCase()} onClick={()=>onMeeting(m)} title={`${name(m.staff_id)} · ${manager(m.manager_id)} · ${m.status}`}><strong>{time(m)} · {name(m.staff_id)}</strong><span>{manager(m.manager_id)} · {m.type}</span><span>{m.status==='Scheduled'&&dayOf(m)<today()?'Awaiting outcome':m.status}</span></button>}
 return <div className="calendar-workspace"><section className="panel calendar-panel"><div className="calendar-toolbar"><div className="calendar-navigation"><button aria-label="Previous month" onClick={()=>changeMonth(-1)}><ChevronLeft size={18}/></button><h2 aria-live="polite">{new Intl.DateTimeFormat('en-US',{month:'long',year:'numeric',timeZone:'UTC'}).format(first)}</h2><button aria-label="Next month" onClick={()=>changeMonth(1)}><ChevronRight size={18}/></button><button onClick={()=>setMonth(today().slice(0,7))}>Today</button></div><div className="actions"><button aria-pressed={layout==='calendar'} className={layout==='calendar'?'primary':''} onClick={()=>setLayout('calendar')}>Calendar</button><button aria-pressed={layout==='agenda'} className={layout==='agenda'?'primary':''} onClick={()=>setLayout('agenda')}>Agenda</button></div></div><div className="filters"><input aria-label="Search calendar" placeholder="Search employee or manager" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Calendar department" value={department} onChange={e=>setDepartment(e.target.value)}><option value="">FOH + BOH</option><option>FOH</option><option>BOH</option></select><select aria-label="Calendar meeting status" value={status} onChange={e=>setStatus(e.target.value)}>{['Scheduled','Completed','Missed','Cancelled','All'].map(s=><option key={s}>{s}</option>)}</select></div><div className="calendar-legend"><span className="chip blue">Scheduled</span><span className="chip yellow">Needs scheduling</span><span className="chip orange">Six-month overdue</span><span className="chip purple">GM request</span><small>Central time · Reminders clear only after completion</small></div>
 {layout==='calendar'?<div className="calendar-scroll"><div className="month-grid">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(d=><div className="weekday" key={d}>{d}</div>)}{Array.from({length},(_,i)=>{const date=new Date(Date.UTC(year,mon-1,i-offset+1)).toISOString().slice(0,10),inMonth=date.startsWith(month),items=meetings.filter(m=>dayOf(m)===date);return <div key={date} className={'calendar-day'+(!inMonth?' outside':'')+(date===today()?' current-day':'')}><div className="day-heading"><span aria-label={date} aria-current={date===today()?'date':undefined}>{Number(date.slice(-2))}</span>{date>=today()&&<button aria-label={'Schedule meeting on '+date} title="Schedule on this day" onClick={()=>onSchedule(undefined,date)}><Plus size={14}/></button>}</div>{items.map(event)}</div>})}</div></div>:<div className="calendar-agenda">{visible.length?visible.map(m=><div key={m.id} className="agenda-item"><time>{dayOf(m)}</time>{event(m)}</div>):<div className="empty"><strong>No matching meetings this month</strong><p>Choose another month, adjust the filters, or schedule a meeting.</p></div>}</div>}
 <div className="panel-footer">{visible.length} matching {visible.length===1?'meeting':'meetings'} this month. Past bookings remain open until you record an outcome.</div></section>
 <section className="panel calendar-attention"><div className="section-title"><div><h2>People needing attention</h2><p className="muted">Across all dates · Booking status and meeting reminders are separate.</p></div><span className="count">{attention.length}</span></div>{attention.length?attention.map(p=>{const l=labels(p,data),booking=data.meetings.filter(m=>m.staff_id===p.id&&m.status==='Scheduled').sort((a,b)=>a.scheduled_at.localeCompare(b.scheduled_at))[0],overdue=!!l.due&&l.due<today();return <div key={p.id} className={'person-row attention-'+(booking?'booked':overdue?'overdue':'unbooked')}><div className="grow"><strong>{name(p.id)}</strong><small>{p.department} · {l.due?'Six-month due '+l.due:'No completed meeting'}</small>{booking&&<small>Booking: {dayOf(booking)} · {time(booking)}</small>}</div><div className="chips"><span className={'chip '+(booking?'blue':overdue?'orange':'yellow')}>{booking?'Scheduled':overdue?'Overdue · not scheduled':'Needs scheduling'}</span>{booking&&overdue&&<span className="chip orange">Six-month overdue</span>}{l.priority&&!overdue&&<span className="chip orange">Priority meeting</span>}{l.requested&&<span className="chip purple">GM requested</span>}</div><button onClick={()=>booking?onMeeting(booking):onSchedule(p)}>{booking?'View booking':'Schedule'}</button></div>}):<div className="empty"><strong>No matching staff need attention</strong><p>Due dates, priority flags, and GM requests will appear here.</p></div>}</section></div>
}
