import {setPracticeIsolation} from './practiceIsolation';
import {useEffect,useRef,useState} from 'react';
import {supabase} from './client';
import {availableChapters,type Chapter} from './walkthroughs';
import type {SchedulerData,Workspace} from './scheduler';
import {Modal} from './SchedulerForms';
import {PracticeWorkspace} from './PracticeWorkspace';
import type {PracticeRole} from './practiceModel';
export type Progress={chapter:string;content_version:number;status:string;step:number};
export function learningAction(chapter?:string,practice?:PracticeRole,restart=false){window.dispatchEvent(new CustomEvent('stars:learn',{detail:{chapter,practice,restart}}))}
export function LearningLinks({data,workspace,search=''}:{data:SchedulerData;workspace:Workspace;search?:string}){const [progress,setProgress]=useState<Progress[]>([]);useEffect(()=>{const update=(e:Event)=>setProgress((e as CustomEvent<Progress[]>).detail);window.addEventListener('stars:progress',update);window.dispatchEvent(new Event('stars:progress-request'));return()=>window.removeEventListener('stars:progress',update)},[]);const allowed=availableChapters(data,workspace).filter(c=>(c.title+' walkthrough tutorial '+c.steps.map(s=>s.title+' '+s.text).join(' ')).toLowerCase().includes(search.toLowerCase()));return <section className="panel scheduler-card" data-tour="help-center"><h2>Walkthroughs & practice</h2><p>Resume a tour, restart a chapter, or learn with fictional records.</p>{allowed.map(c=><div className="actions" key={c.id}><strong>{c.title}</strong><span>{progress.find(p=>p.chapter===c.id)?.status.replace('_',' ')||'Not started'}</span><button onClick={()=>learningAction(c.id)}>Start / resume</button><button onClick={()=>learningAction(c.id,undefined,true)}>Restart</button></div>)}<div className="actions">{(workspace==='employee'?['employee']:data.self.is_admin?['manager','it']:['manager']).map(role=><button key={role} onClick={()=>learningAction(undefined,role as PracticeRole)}>Practice {role} tasks</button>)}</div></section>}
export function Onboarding({data,workspace,preview,go,canLeave}:{data:SchedulerData;workspace:Workspace;preview:boolean;go:(page:string)=>void;canLeave:()=>boolean}){
 const allowed=availableChapters(data,workspace),[progress,setProgress]=useState<Progress[]|null>(null),[error,setError]=useState(''),[offer,setOffer]=useState(false),[tour,setTour]=useState<{chapter:Chapter;step:number}|null>(null),[practice,setPractice]=useState<PracticeRole|null>(null),[missing,setMissing]=useState(false);
 const origin=useRef<{url:string;y:number;focus:HTMLElement|null;groups:{label:string;open:boolean}[]}|null>(null),offered=useRef(new Set<string>());
 const saveQueue=useRef<Promise<void>>(Promise.resolve());
 useEffect(()=>{const emit=()=>window.dispatchEvent(new CustomEvent('stars:progress',{detail:progress||[]}));emit();window.addEventListener('stars:progress-request',emit);return()=>window.removeEventListener('stars:progress-request',emit)},[progress]);
 const targetChapter=workspace==='employee'?'employee':workspace==='it'?'it':'manager';
 useEffect(()=>{let live=true;setProgress(null);setError('');if(preview){setProgress([]);return}void supabase!.rpc('onboarding_read').then(r=>{if(live){if(r.error)setError('Walkthrough progress is unavailable. You can still use Help and practice.');else setProgress(r.data)}});return()=>{live=false}},[data.self.id,preview]);
 useEffect(()=>{if(progress&&!progress.some(p=>p.chapter===targetChapter)&&!offered.current.has(targetChapter)&&!tour&&!practice){offered.current.add(targetChapter);setOffer(true)}},[progress,targetChapter,tour,practice]);
 async function save(chapter:string,status:string,step=0){const item={chapter,content_version:1,status,step};setProgress(p=>[...(p||[]).filter(x=>x.chapter!==chapter),item]);if(preview)return;saveQueue.current=saveQueue.current.then(async()=>{const r=await supabase!.rpc('onboarding_save',{p_chapter:chapter,p_content_version:1,p_status:status,p_step:step});if(r.error)setError('Your walkthrough progress could not be saved. You can restart it from Help.');}).catch(()=>setError('Walkthrough progress could not be saved. Use Help to restart.'));await saveQueue.current;}
 function remember(){origin.current={url:location.href,y:scrollY,focus:document.activeElement as HTMLElement,groups:Array.from(document.querySelectorAll<HTMLButtonElement>('.nav-group-toggle')).map(b=>({label:b.textContent||'',open:b.getAttribute('aria-expanded')==='true'}))}}
 useEffect(()=>()=>setPracticeIsolation(false),[]);
 function restore(){setPracticeIsolation(false);const o=origin.current;setTour(null);setPractice(null);if(!o)return;history.replaceState(null,'',o.url);window.dispatchEvent(new PopStateEvent('popstate'));requestAnimationFrame(()=>{requestAnimationFrame(()=>{for(const b of document.querySelectorAll<HTMLButtonElement>('.nav-group-toggle')){const old=o.groups.find(g=>g.label.replace(/[▾▸]/g,'')===(b.textContent||'').replace(/[▾▸]/g,''));if(old&&old.open!==(b.getAttribute('aria-expanded')==='true'))b.click()}window.scrollTo(0,o.y);if(o.focus?.isConnected)o.focus.focus()})});origin.current=null}
 function start(chapter:Chapter,step=0){if(!canLeave())return;remember();setOffer(false);const n=Math.min(step,chapter.steps.length-1);setTour({chapter,step:n});void save(chapter.id,'in_progress',n);go(chapter.steps[n].page)}
 useEffect(()=>{const handle=(e:Event)=>{const detail=(e as CustomEvent<{chapter?:string;practice?:PracticeRole;restart?:boolean}>).detail;if(detail.practice){if(!(workspace==='employee'?detail.practice==='employee':detail.practice==='manager'&&data.self.is_manager||detail.practice==='it'&&data.self.is_admin)||!canLeave())return;remember();setOffer(false);setPracticeIsolation(true);setPractice(detail.practice);return}const chapter=allowed.find(c=>c.id===detail.chapter);if(chapter){const old=progress?.find(p=>p.chapter===chapter.id);start(chapter,detail.restart||old?.status==='completed'?0:old?.step||0)}};window.addEventListener('stars:learn',handle);return()=>window.removeEventListener('stars:learn',handle)},[workspace,data.self.is_admin,data.self.is_manager,progress,canLeave]);
 useEffect(()=>{if(!tour)return;if(!allowed.some(c=>c.id===tour.chapter.id)){restore();return}const step=tour.chapter.steps[tour.step];const target=document.querySelector<HTMLElement>('[data-tour="'+step.target+'"]');setMissing(!target);const details=target instanceof HTMLDetailsElement?target:null;const wasOpen=details?.open;if(details)details.open=true;target?.classList.add('tour-highlight');target?.scrollIntoView({block:'nearest',behavior:'instant'});return()=>{target?.classList.remove('tour-highlight');if(details)details.open=!!wasOpen}},[tour,workspace]);
 function move(step:number){if(!tour)return;setTour({...tour,step});void save(tour.chapter.id,'in_progress',step);go(tour.chapter.steps[step].page)}
 return <>{error&&<p className="notice" role="status">{error}</p>}{offer&&!tour&&!practice&&<section className="onboarding-offer" aria-label="First-time walkthrough"><strong>Welcome to {workspace==='it'?'IT View':workspace==='manager'?'Manager View':'Employee View'}.</strong><span>Take a short tour, or return to it in Help.</span><button onClick={()=>{const c=allowed.find(c=>c.id===targetChapter);if(c)start(c)}}>Start tour</button><button onClick={()=>{setOffer(false);void save(targetChapter,'deferred')}}>Not now</button>{workspace==='it'&&!progress?.some(p=>p.chapter==='manager'&&p.status==='completed')&&<button onClick={()=>start(allowed.find(c=>c.id==='manager')!)}>Start manager essentials</button>}</section>}{tour&&<div className="walkthrough-overlay"><Modal title={tour.chapter.steps[tour.step].title} onClose={()=>{void save(tour.chapter.id,'deferred',tour.step);restore()}}><p aria-live="polite">{tour.chapter.title} · Step {tour.step+1} of {tour.chapter.steps.length}</p><p>{tour.chapter.steps[tour.step].text}</p>{missing&&<p>The highlighted control is not available on this page yet. You can continue reading or return to Help for practice.</p>}<p className="muted">This tour never saves or publishes records.</p><div className="actions"><button disabled={tour.step===0} onClick={()=>move(tour.step-1)}>Back</button><button onClick={()=>{void save(tour.chapter.id,'deferred',tour.step);restore()}}>Skip / exit</button>{tour.step<tour.chapter.steps.length-1?<button className="primary" onClick={()=>move(tour.step+1)}>Next</button>:<button className="primary" onClick={()=>{void save(tour.chapter.id,'completed',tour.step);restore()}}>Finish</button>}</div></Modal></div>}{practice&&<PracticeWorkspace role={practice} onExit={restore} onComplete={()=>void save('practice_'+practice,'completed')}/>}</>;
}
