import {useEffect,useState} from 'react';
import {supabase} from './client';
import {clockTime,type SchedulerData,type WorkShift,centralInstant,addDays,weekOf} from './scheduler';
export type HoursFlag={person_id:string;name:string;week:string;hours:number};
export type CoverageInterval={day:string;period:string;job_id:string;job:string;start:string;end:string;needed:number;scheduled:number;shortage:number;excess:number;minutes:number};
export type Planning={hours:HoursFlag[];coverage:CoverageInterval[];missing:{day:string;message:string}[];requires_ack:boolean;fingerprint:string;before_hours?:HoursFlag[];coverage_unchanged?:boolean;before?:WorkShift[];after?:WorkShift[]};
export function hoursLabel(hours:number){return hours>40?`Projected OT · ${hours.toFixed(2)}h · ${(hours-40).toFixed(2)}h over 40`:hours>=35?`Approaching OT · ${hours.toFixed(2)}h`:`${hours.toFixed(2)}h`}
export function localHours(data:SchedulerData,shifts:WorkShift[],week:string):HoursFlag[]{
 const all=[...data.published.filter(w=>w.week!==week).flatMap(w=>w.shifts),...shifts];
 const from=Date.parse(centralInstant(week+'T00:00')),to=Date.parse(centralInstant(addDays(week,7)+'T00:00'));
 const unique=[...new Map(all.map(s=>[s.id,s])).values()];
 return data.people.filter(p=>p.employment_type!=='Salaried').map(p=>({person_id:p.id,name:p.name,week,hours:unique.filter(s=>s.person_id===p.id).reduce((n,s)=>n+Math.max(0,Math.min(to,Date.parse(s.end))-Math.max(from,Date.parse(s.start)))/3600000,0)})).filter(p=>p.hours>0);
}
export function PlanningSummary({value}:{value:Planning}){return <div className="planning-summary"><h3>Hours & coverage review</h3><p className="muted">All jobs included · 35+ hours require acknowledgment · OT is projected above 40 hours · Salaried assignments and PTO excluded</p>{value.hours.filter(h=>h.hours>=35).map(h=><p className={h.hours>40?'error':'notice'} key={h.week+h.person_id}><strong>{h.name}</strong> · Week of {h.week} · {hoursLabel(h.hours)}</p>)}{!value.hours.some(h=>h.hours>=35)&&<p>No employees at 35+ scheduled hours.</p>}{value.before_hours&&<details><summary>Before / after weekly hours</summary>{value.hours.map(h=><p key={h.week+h.person_id}>{h.name} · {h.week}: {value.before_hours!.find(b=>b.week===h.week&&b.person_id===h.person_id)?.hours||0}h → {h.hours}h</p>)}</details>}{value.coverage_unchanged&&<p>Coverage unchanged by this reassignment.</p>}{[...new Set([...value.coverage.map(c=>c.day),...value.missing.map(m=>m.day)])].sort().map(day=>{const rows=value.coverage.filter(c=>c.day===day),missing=value.missing.filter(m=>m.day===day),short=rows.filter(c=>c.shortage>0);return <details key={day} className={missing.length||short.length?'coverage-gap':'coverage-ok'}><summary>{day} · {missing.length?'Coverage setup needed':short.length?`${short.length} understaffed intervals · ${Math.round(short.reduce((n,c)=>n+c.minutes*c.shortage,0))} person-minutes short`:'Targets met'}{rows.some(c=>c.excess>0)?' · Excess coverage':''}</summary>{missing.map((m,i)=><p className="notice" key={i}>{m.message}</p>)}{rows.map((c,i)=><p key={i}>{c.period} · {c.job} · {clockTime(c.start)}–{clockTime(c.end)}: {c.scheduled}/{c.needed} people{c.shortage>0?` · Short ${c.shortage}`:c.excess>0?` · ${c.excess} extra`:''}</p>)}</details>})}</div>}
export function Acknowledgment({value}:{value:Planning}){return <>{value.requires_ack&&<><label className="check"><input name="acknowledged" type="checkbox" required/>I reviewed all 35+ hour warnings, coverage shortages, and missing setup.</label><label>Reason for proceeding<textarea name="review_reason" minLength={3} maxLength={2000} required/></label></>}<input type="hidden" name="fingerprint" value={value.fingerprint}/></>}
export function PlanningReport({week,preview=false}:{week:string;preview?:boolean}){const [value,setValue]=useState<Planning|null>(null),[error,setError]=useState('');useEffect(()=>{let current=true;setValue(null);if(preview)return;void supabase?.rpc('planning_read',{p_week:weekOf(week)}).then(r=>{if(current){setError(r.error?.message||'');setValue(r.data)}});return()=>{current=false}},[week,preview]);return <section className="panel scheduler-card"><h2>Planning · Week of {weekOf(week)}</h2>{preview?<p>Connect a test account to assess hours and coverage.</p>:error?<p className="error">{error}</p>:value?<PlanningSummary value={value}/>:<p>Loading hours and coverage…</p>}</section>}
