import {useState} from 'react';
import {practiceStart,practiceReduce,practiceHours,practiceIssues,type PracticeRole,type PracticeAction} from './practiceModel';
import {Modal} from './SchedulerForms';
export function PracticeWorkspace({role,onExit,onComplete}:{role:PracticeRole;onExit:()=>void;onComplete:()=>void}){
 const [state,setState]=useState(()=>practiceStart(role)),[error,setError]=useState(''),[reported,setReported]=useState(false);
 const send=(a:PracticeAction)=>{try{const next=practiceReduce(state,a);setState(next);setError('');if(next.completed&&!reported){setReported(true);onComplete()}}catch(e){setError((e as Error).message)}};
 const changed=state.draft||state.requests.length>0||state.people.length>2||state.published;
 function exit(){if(!changed||state.completed||confirm('Leave this unfinished practice exercise? Fictional changes will be discarded.'))onExit()}
 return <Modal title={role==='it'?'IT practice':role==='manager'?'Manager practice':'Employee practice'} onClose={exit}><div className="practice-workspace"><p className="practice-banner" role="status">Practice — fictional data, nothing affects your store</p><p>Only the tasks below are simulated. Other tools are available in the walkthroughs. No email, credentials, or real schedule changes are created.</p><div className="actions"><button onClick={()=>{if(!changed||confirm('Reset this fictional exercise?')){setState(practiceStart(role));setError('');setReported(false)}}}>Reset practice</button><button onClick={exit}>Exit practice</button></div>
 {role==='manager'&&<><h3>Build and review a week</h3><p>Alex Example starts with 32 hours. Add a Lunch GSR preset, try an overlapping shift, remove the conflict, and review the hours and missing coverage setup before a simulated release.</p>{!state.draft&&!state.published&&<button onClick={()=>send({type:'draft'})}>Create practice draft</button>}{state.draft&&<><button onClick={()=>send({type:'shift',shift:{id:'lunch',person:'alex',day:5,start:11,end:16,job:'GSR'}})}>Use Lunch GSR preset · Friday 11–4</button><button onClick={()=>send({type:'shift',shift:{id:'conflict',person:'alex',day:0,start:12,end:16,job:'GSR'}})}>Try an overlapping shift</button></>}{state.shifts.map(s=><p key={s.id}>Alex Example · {['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'][s.day]} · {s.start}:00–{s.end}:00 · {s.job}{state.draft&&<button onClick={()=>send({type:'remove',id:s.id})}>Remove {s.id==='conflict'?'conflict':'shift'}</button>}</p>)}<p>{practiceHours(state)} hours · {practiceHours(state)>40?'Projected OT':practiceHours(state)>=35?'Approaching OT':'Below 35 hours'}</p><p className="warning">Coverage setup needed — this example has no configured staffing rules.</p>{practiceIssues(state).map(x=><p className="error" key={x}>{x}</p>)}{state.draft&&<form onSubmit={e=>{e.preventDefault();send({type:'review',reason:String(new FormData(e.currentTarget).get('reason'))})}}><label className="check"><input type="checkbox" required/>I reviewed the hours and missing coverage setup.</label><label>Reason<textarea name="reason" minLength={3} required/></label><button>Review practice schedule</button></form>}{state.reviewed&&state.draft&&<button onClick={()=>send({type:'publish'})}>Simulate release</button>}{state.published&&<p className="success">Practice schedule published. No real schedule changed.</p>}</>}
 {role==='employee'&&<><h3>Your example shift</h3><p>Alex Example · Friday · GSR · 11:00 AM–4:00 PM</p><button onClick={()=>send({type:'request',kind:'Time off'})}>Request time off for another day</button><button onClick={()=>send({type:'request',kind:'Offer shift'})}>Offer this shift</button>{state.requests.map(r=><article className="panel scheduler-card" key={r.id}><strong>{r.kind} · {r.status}</strong>{r.status==='Waiting on coworker'&&<button onClick={()=>send({type:'accept',id:r.id})}>Simulate coworker claiming</button>}{r.status==='Waiting on manager'&&<button onClick={()=>send({type:'approve',id:r.id})}>Simulate manager approval</button>}</article>)}<p>These simulation buttons explain the sequence. Employees cannot approve their own live requests.</p></>}
 {role==='it'&&<><h3>Create a fictional teammate and account</h3><form onSubmit={e=>{e.preventDefault();send({type:'person',name:String(new FormData(e.currentTarget).get('name'))});e.currentTarget.reset()}}><label>Fictional name<input name="name" required placeholder="Jamie Example" maxLength={80}/></label><button>Add fictional teammate</button></form>{state.people.map(p=><article key={p.id}><p>{p.name} · {p.role}</p>{p.role==='No account'&&<form onSubmit={e=>{e.preventDefault();send({type:'account',id:p.id,role:String(new FormData(e.currentTarget).get('role'))})}}><label>Example account type<select name="role"><option>Employee</option><option>hSHL</option><option>sSHL</option></select></label><p>hSHL does not grant schedule management; sSHL does. No actual login or password is generated here.</p><button>Simulate creating account</button></form>}</article>)}</>}
 {error&&<p className="error" role="alert">{error}</p>}{state.completed&&<p className="success" role="status">Exercise completed. You can reset it to practice again or return to your workspace.</p>}</div></Modal>;
}
