import {useEffect,useId,useRef,useState,type ReactNode} from 'react';
import {centralInstant,localCandidates,localFields,type SchedulerData,type WorkShift,type LinkedTraining} from './scheduler';
import {positionName,today} from './domain';
export function Modal({title,children,onClose,busy=false}:{title:string;children:ReactNode;onClose:()=>void;busy?:boolean}){
 const ref=useRef<HTMLDivElement>(null),initial=useRef(''),id=useId();
 const snapshot=()=>JSON.stringify(Array.from(ref.current?.querySelectorAll<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>('input,select,textarea')||[]).map(x=>[x.name,x.type==='checkbox'?(x as HTMLInputElement).checked:x.value]));
 function close(){if(!busy&&(initial.current===snapshot()||confirm('Discard unsaved changes?')))onClose()}
 useEffect(()=>{initial.current=snapshot();const previous=document.activeElement as HTMLElement;ref.current?.querySelector<HTMLElement>('button,input,select')?.focus();return()=>{if(previous?.isConnected)previous.focus()}},[]);
 useEffect(()=>{const handler=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();close()}if(e.key==='Tab'){const nodes=Array.from(ref.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),a[href]')||[]);if(e.shiftKey&&document.activeElement===nodes[0]){e.preventDefault();nodes.at(-1)?.focus()}else if(!e.shiftKey&&document.activeElement===nodes.at(-1)){e.preventDefault();nodes[0]?.focus()}}};document.addEventListener('keydown',handler);return()=>document.removeEventListener('keydown',handler)});
 return <div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div ref={ref} className="modal scheduler-modal" role="dialog" aria-modal="true" aria-labelledby={id}><div className="modal-heading"><h2 id={id}>{title}</h2><button type="button" aria-label="Close dialog" onClick={close} disabled={busy}>×</button></div>{children}</div></div>
}
export function CentralField({name,label,value,min,onChange}:{name:string;label:string;value:string;min?:string;onChange?:(value:string)=>void}){
 const [current,setCurrent]=useState(value);const ambiguous=localCandidates(current).length>1;
 return <div><label>{label}<input type="datetime-local" name={name} required value={current} min={min} onChange={e=>{setCurrent(e.target.value);onChange?.(e.target.value)}}/></label>{ambiguous&&<label>This Central time occurs twice<select name={name+'Occurrence'} required defaultValue=""><option value="" disabled>Choose occurrence</option><option value="earlier">First occurrence · daylight time</option><option value="later">Second occurrence · standard time</option></select></label>}</div>
}
export const dateValue=(f:FormData,name:string)=>centralInstant(String(f.get(name)),String(f.get(name+'Occurrence')||''));
export function ShiftForm({data,shift,date,onSave,busy,error}:{data:SchedulerData;shift?:WorkShift;date:string;onSave:(s:WorkShift)=>Promise<void>;busy:boolean;error:string}){
 const [person,setPerson]=useState(shift?.person_id||''),[job,setJob]=useState(shift?.job_id||''),[validation,setValidation]=useState('');const selected=data.people.find(p=>p.id===person);
 return <form onSubmit={e=>{e.preventDefault();setValidation('');const f=new FormData(e.currentTarget);try{void onSave({id:shift?.id||crypto.randomUUID(),person_id:person,job_id:selected?.group==='SHL'?null:job,slot:shift?.slot||1,start:dateValue(f,'start'),end:dateValue(f,'end'),qualification_reason:shift?.qualification_reason||''})}catch(err){setValidation((err as Error).message)}}}><fieldset disabled={busy}><label>Team member<select required value={person} onChange={e=>{setPerson(e.target.value);setJob(data.people.find(p=>p.id===e.target.value)?.primary_job_id||'')}}><option value="">Choose a person</option>{data.people.filter(p=>p.active&&p.on_roster).map(p=><option value={p.id} key={p.id}>{p.name} · {positionName(p.group)}</option>)}</select></label>{selected?.group==='SHL'?<p>Position: SHL</p>:<label>Job assignment<select required value={job} onChange={e=>setJob(e.target.value)}><option value="">Choose a job</option>{data.jobs.filter(j=>j.active).map(j=><option key={j.id} value={j.id}>{positionName(j.department)} · {j.name}</option>)}</select></label>}<div className="form-grid"><CentralField name="start" label="Start (Central)" value={shift?localFields(shift.start):date+'T11:00'}/><CentralField name="end" label="End (Central)" value={shift?localFields(shift.end):date+'T17:00'}/></div><p className="muted">Work shifts can extend beyond customer opening hours. Draft conflicts must be resolved before release.</p>{(error||validation)&&<p className="error" role="alert">{error||validation}</p>}<button className="primary" disabled={busy}>{busy?'Saving…':'Save to draft'}</button></fieldset></form>
}
export function TrainingForm({data,initial,revision,onSave,busy,error}:{data:SchedulerData;initial?:LinkedTraining;revision?:string;onSave:(p:Record<string,unknown>)=>Promise<void>;busy:boolean;error:string}){
 const allPublished=data.published.flatMap(w=>w.shifts);const shifts=revision&&data.week.draft?.id===revision?data.week.draft.shifts:allPublished;
 const [trainee,setTrainee]=useState(initial?.work_shift_id||''),[trainer,setTrainer]=useState(initial?.trainer_shift_id||''),[job,setJob]=useState(initial?.training_position_id||''),[start,setStart]=useState(initial?localFields(initial.scheduled_at):today()+'T11:00'),[end,setEnd]=useState(initial?.ends_at?localFields(initial.ends_at):today()+'T12:00'),[validation,setValidation]=useState('');
 const selected=shifts.find(s=>s.id===trainee);const personName=(id:string)=>data.people.find(p=>p.id===id)?.name||'Former teammate';
 const candidates=[...shifts,...allPublished.filter(p=>!shifts.some(s=>s.id===p.id))].filter(s=>data.people.some(p=>p.id===s.person_id&&p.is_trainer&&p.active)&&s.person_id!==selected?.person_id);
 return <form onSubmit={e=>{e.preventDefault();setValidation('');const f=new FormData(e.currentTarget);try{const tr=candidates.find(s=>s.id===trainer);if(!selected||!tr)throw Error('Choose both work shifts.');void onSave({staff_id:selected.person_id.slice(2),trainer_id:tr.person_id.slice(2),training_position_id:job,shift:selected.slot,scheduled_at:dateValue(f,'start'),ends_at:dateValue(f,'end'),work_shift_id:selected.id,trainer_shift_id:tr.id,schedule_revision_id:revision||null})}catch(err){setValidation((err as Error).message)}}}><fieldset disabled={busy}><p className="muted">{revision?'This training stays private until this draft is released.':'Choose the trainee and trainer from published work shifts.'}</p><label>Trainee’s work shift<select required value={trainee} onChange={e=>{setTrainee(e.target.value);setTrainer('');const s=shifts.find(s=>s.id===e.target.value);if(s){setStart(localFields(s.start));setEnd(localFields(s.end))}}}><option value="">Choose a work shift</option>{shifts.filter(s=>s.person_id.startsWith('s:')&&new Date(s.end)>new Date()).map(s=><option key={s.id} value={s.id}>{personName(s.person_id)} · {localFields(s.start).replace('T',' ')}–{localFields(s.end).slice(11)}</option>)}</select></label><label>Job being learned<select required value={job} onChange={e=>setJob(e.target.value)}><option value="">Choose a job</option>{data.jobs.filter(j=>j.active).map(j=><option key={j.id} value={j.id}>{positionName(j.department)} · {j.name}</option>)}</select></label><label>Trainer’s work shift<select required value={trainer} onChange={e=>setTrainer(e.target.value)}><option value="">Choose a trainer</option>{candidates.map(s=><option key={s.id} value={s.id}>{personName(s.person_id)} · {localFields(s.start).replace('T',' ')}–{localFields(s.end).slice(11)}</option>)}</select></label><div className="form-grid"><CentralField key={'s'+start} name="start" label="Training starts (Central)" value={start}/><CentralField key={'e'+end} name="end" label="Training ends (Central)" value={end}/></div><p className="muted">Both people must be working for this entire interval. Training progress is linked to the selected work shift automatically.</p>{(validation||error)&&<p className="error" role="alert">{validation||error}</p>}<button className="primary" disabled={busy}>{busy?'Saving…':'Save training'}</button></fieldset></form>
}
