import {useState} from 'react';
import {addDays,clockTime,hours,shiftDay,scheduleChanges,centralInstant,type SchedulerData,type WorkShift,type Act} from './scheduler';
import {displayTime,positionName} from './domain';
import {Modal,ShiftForm,CentralField,dateValue} from './SchedulerForms';
export function ScheduleBoard({data,week,setWeek,act,busy,onTraining}:{data:SchedulerData;week:string;setWeek:(w:string)=>void;act:Act;busy:boolean;onTraining:(revision?:string)=>void}){
 const [group,setGroup]=useState(''),[mode,setMode]=useState('team'),[editing,setEditing]=useState<{date:string;shift?:WorkShift;version:number}|null>(null),[review,setReview]=useState<{issues:string[];version:number}|null>(null),[error,setError]=useState(''),[issues,setIssues]=useState<string[]>([]),[releaseMode,setReleaseMode]=useState('now');
 const draft=data.week.draft,manager=data.self.is_manager,published=data.published.find(p=>p.week===week)?.shifts||[],shifts=manager&&draft?draft.shifts:published;
 const editable=manager&&draft&&draft.state!=='Queued';
 const people=data.people.filter(p=>(p.on_roster||shifts.some(s=>s.person_id===p.id))&&(p.active||shifts.some(s=>s.person_id===p.id))&&(!group||p.group===group)&&(mode!=='mine'||p.id===data.self.person_id));
 const job=(s:WorkShift)=>s.job_id?data.jobs.find(j=>j.id===s.job_id)?.name||'Archived job':'SHL';
 const name=(s:WorkShift)=>data.people.find(p=>p.id===s.person_id)?.name||'Former teammate';
 async function run(action:string,p:Record<string,unknown>){setError('');try{return await act(action,p)}catch(e){setError((e as Error).message);throw e}}
 async function save(shifts:WorkShift[]){if(!draft)return;if(editing&&editing.version!==draft.version){setError('This draft changed while the form was open. Close it and reopen the shift.');return}const result=await run('save',{id:draft.id,version:draft.version,shifts});setIssues((result.issues as string[])||[]);setEditing(null)}
 const changes=scheduleChanges(published,shifts);
 return <><section className="panel schedule-panel"><div className="schedule-controls"><div className="actions"><button aria-label="Previous week" onClick={()=>{setWeek(addDays(week,-7));setIssues([]);setError('')}}>←</button><h2>Week of {week}</h2><button aria-label="Next week" onClick={()=>{setWeek(addDays(week,7));setIssues([]);setError('')}}>→</button></div><div className="actions"><button aria-pressed={mode==='team'} onClick={()=>setMode('team')}>Team schedule</button><button aria-pressed={mode==='mine'} onClick={()=>setMode('mine')}>My schedule</button><select aria-label="Schedule position group" value={group} onChange={e=>setGroup(e.target.value)}><option value="">All positions</option>{['FOH','BOH','Catering','SHL'].map(g=><option key={g} value={g}>{positionName(g)}</option>)}</select></div></div>
 <div className={'schedule-state '+(draft?.state==='Queued'?'purple':draft?'yellow':'blue')}><strong>{manager&&draft?draft.state==='Queued'?'Scheduled for release':draft.state==='Attention'?'Release needs attention':'Private draft':data.published.some(p=>p.week===week)?'Published schedule':'No schedule released yet'}</strong>{draft?.state==='Queued'?<span>{draft.release_at&&displayTime(draft.release_at)} Central · {draft.release_name} · Locked until release or cancellation</span>:<span>{draft?'Changes are saved privately. Employees still see the last release.':'Employees can see published work shifts. Meetings and training details stay personal.'}</span>}</div>
 {manager&&<div className="schedule-actions actions">{!draft?<><button className="primary" disabled={busy} onClick={()=>void run('draft',{week}).catch(()=>{})}>Create draft</button><button disabled={busy} onClick={()=>void run('draft',{week,copy_previous:true}).catch(()=>{})}>Copy previous week</button></>:draft.state==='Queued'?<button disabled={busy} onClick={()=>{if(confirm('Cancel this queued release? The draft and published schedule will remain.'))void run('unqueue',{id:draft.id,version:draft.version}).catch(()=>{})}}>Cancel queued release</button>:<><button onClick={()=>setEditing({date:week,version:draft.version})} disabled={busy}>Add work shift</button><button disabled={busy} onClick={()=>onTraining(draft.id)}>Add draft training</button><button className="primary" disabled={busy} onClick={()=>void run('review',{id:draft.id,version:draft.version}).then(r=>{setReview({issues:r.issues as string[],version:draft.version});setReleaseMode('now')}).catch(()=>{})}>Review & release</button>{draft.base_id!==data.week.published_id&&<button disabled={busy} onClick={()=>{if(confirm('Replace this stale draft with the current published schedule? Draft work-shift edits will be preserved in change history.'))void run('rebase',{id:draft.id,version:draft.version}).catch(()=>{})}}>Reload published version</button>}</>}</div>}
 {(error||draft?.error)&&<p className="error" role="alert">{error||draft?.error}</p>}{issues.length>0&&<div className="error"><strong>Resolve before release</strong><ul>{issues.map((v,i)=><li key={i}>{v}</li>)}</ul></div>}
 <div className="schedule-scroll"><table className="week-board"><caption className="sr-only">Sunday–Saturday work schedule. All times Central.</caption><thead><tr><th>Team member</th>{Array.from({length:7},(_,i)=><th key={i}>{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][i]}<small>{addDays(week,i).slice(5)}</small></th>)}<th>Hours</th></tr></thead><tbody>{people.map(p=><tr key={p.id}><th scope="row">{p.name}<small>{positionName(p.group)}{p.is_ca?' · CA':''}</small><small>{p.primary_job_id?data.jobs.find(j=>j.id===p.primary_job_id)?.name:''}</small></th>{Array.from({length:7},(_,i)=>{const day=addDays(week,i),items=shifts.filter(s=>s.person_id===p.id&&shiftDay(s.start)===day);return <td key={i}>{items.map(s=><button key={s.id} className={'work-shift '+(draft?'draft-shift':'published-shift')} disabled={!editable||busy} onClick={()=>{setError('');setEditing({date:day,shift:s,version:draft!.version})}}><strong>{clockTime(s.start)}–{clockTime(s.end)}{shiftDay(s.start)!==shiftDay(s.end)?' +1 day':''}</strong><span>{job(s)} · Shift {s.slot}</span>{data.training.some(t=>t.status==='Scheduled'&&(t.work_shift_id===s.id||t.trainer_shift_id===s.id))&&<span>Training scheduled</span>}</button>)}{editable&&<button className="add-shift" aria-label={'Add shift for '+p.name+' on '+day} disabled={busy} onClick={()=>setEditing({date:day,version:draft!.version,shift:{id:crypto.randomUUID(),person_id:p.id,job_id:p.primary_job_id||null,start:centralInstant(day+'T11:00'),end:centralInstant(day+'T17:00'),slot:1}})}>＋</button>}</td>})}<td>{hours(shifts.filter(s=>s.person_id===p.id))}</td></tr>)}</tbody></table></div><div className="mobile-week-list">{Array.from({length:7},(_,i)=>{const day=addDays(week,i),items=shifts.filter(s=>shiftDay(s.start)===day&&people.some(p=>p.id===s.person_id));return <section key={day}><h3>{['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'][i]} · {day.slice(5)}</h3>{items.length?items.map(s=><button key={s.id} className={'work-shift '+(draft?'draft-shift':'published-shift')} disabled={!editable||busy} onClick={()=>setEditing({date:day,shift:s,version:draft!.version})}><strong>{name(s)}</strong><span>{clockTime(s.start)}–{clockTime(s.end)}{shiftDay(s.start)!==shiftDay(s.end)?' +1 day':''} · {job(s)} · Shift {s.slot}</span></button>):<p className="muted">No shifts scheduled.</p>}{editable&&<button onClick={()=>setEditing({date:day,version:draft!.version})}>Add shift</button>}</section>})}</div>{!people.length&&<div className="empty">No team members match this view.</div>}<p className="panel-footer">Central time · {hours(shifts.filter(s=>people.some(p=>p.id===s.person_id)))} scheduled hours · Planning totals, not payroll</p></section>
 {manager&&<section className="panel release-service"><h2>Release service</h2><p>Last successful check: {data.service.last_worker_at?displayTime(data.service.last_worker_at):'Not installed or not checked yet'}</p>{data.service.last_worker_at&&Date.now()-Date.parse(data.service.last_worker_at)>180000&&<p className="error">The release service has not checked recently. An IT Admin should inspect the scheduled job.</p>}{data.releases.map(r=><p key={r.id}><strong>{r.week} · {r.state==='Queued'?'Scheduled for release':'Needs attention'}</strong> {r.release_at&&displayTime(r.release_at)} · {r.release_name}{r.error&&<span className="error">{r.error}</span>}</p>)}</section>}
 {editing&&<Modal title={draft?.shifts.some(s=>s.id===editing.shift?.id)?'Edit work shift':'Add work shift'} busy={busy} onClose={()=>{setEditing(null);setError('')}}><ShiftForm data={data} shift={editing.shift} date={editing.date} busy={busy} error={error} onSave={s=>save([...shifts.filter(p=>p.id!==s.id),s]).catch(()=>{})}/>{editing.shift&&draft?.shifts.some(s=>s.id===editing.shift?.id)&&<button className="danger-text" disabled={busy} onClick={()=>{if(confirm('Remove this shift from the draft? The published schedule stays unchanged until release.'))void save(shifts.filter(s=>s.id!==editing.shift?.id)).catch(()=>{})}}>Remove from draft</button>}</Modal>}
 {review&&draft&&<Modal title="Review schedule release" busy={busy} onClose={()=>{setReview(null);setError('')}}>{review.version!==draft.version&&<p className="error">The draft changed after this review. Close this window and review it again.</p>}<p>Week of {week} · {changes.added.length} added · {changes.changed.length} changed · {changes.removed.length} cancelled</p>{(['added','changed','removed'] as const).map(kind=>changes[kind].length>0&&<section key={kind}><h3>{kind==='removed'?'Cancelled':kind[0].toUpperCase()+kind.slice(1)}</h3>{changes[kind].map(s=><p key={s.id}>{name(s)} · {displayTime(s.start)}–{clockTime(s.end)} · {job(s)}</p>)}</section>)}<h3>Associated training</h3>{data.training.filter(t=>t.schedule_revision_id===draft.id||shifts.some(s=>s.id===t.work_shift_id)).map(t=><p key={t.id}>{data.people.find(p=>p.staff_id===t.staff_id)?.name} · {displayTime(t.scheduled_at)} · {t.status}</p>)}{review.issues.length>0?<div className="error"><strong>Fix these issues before release</strong><ul>{review.issues.map((s,i)=><li key={i}>{s}</li>)}</ul></div>:<p className="success">Current checks passed. The server checks again when releasing.</p>}<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const payload:Record<string,unknown>={id:draft.id,version:review.version};if(releaseMode==='later')payload.release_at=dateValue(f,'release');void run(releaseMode==='later'?'queue':'release',payload).then(()=>setReview(null)).catch(()=>{})}catch(err){setError((err as Error).message)}}}><label>Release timing<select value={releaseMode} onChange={e=>setReleaseMode(e.target.value)}><option value="now">Release now</option><option value="later">Choose a release date and time</option></select></label>{releaseMode==='later'&&<><CentralField name="release" label="Release at (Central)" value={week+'T09:00'}/><p className="muted">This locks the reviewed schedule. Cancel the queued release before making further edits.</p></>}{error&&<p role="alert" className="error">{error}</p>}<button className="primary" disabled={busy||review.issues.length>0||review.version!==draft.version}>{busy?'Saving…':releaseMode==='later'?'Lock & schedule release':'Release schedule now'}</button></form></Modal>}</>
}
