import {zone,today,type Training} from './domain.ts';
import type {TrainingPosition,TrainingSignoff} from './trainingProgress.ts';
export type Person={id:string;staff_id?:string;name:string;group:string;active:boolean;on_roster:boolean;is_trainer:boolean;primary_job_id?:string;is_ca?:boolean;version?:number};
export type WorkShift={id:string;person_id:string;start:string;end:string;slot:number;job_id:string|null;qualification_reason?:string};
export type Revision={id:string;state:'Draft'|'Queued'|'Published'|'Attention';version:number;shifts:WorkShift[];base_id:string|null;release_at:string|null;release_name:string;error:string|null};
export type ScheduleRequest={id:string;kind:string;person_id:string;created_by:string;status:string;version:number;reason?:string;response?:string;claimed_by?:string;created_at?:string;decided_at?:string;decided_name?:string;payload:{start?:string;end?:string;effective?:string;days?:number[][][];source?:WorkShift;target?:WorkShift;recipient?:string}};
export type Announcement={id:string;title:string;body:string;groups:string[];active:boolean;version:number;created_by:string;author:string;created_at:string;read:boolean};
export type LinkedTraining=Training&{ends_at?:string;work_shift_id?:string;trainer_shift_id?:string;schedule_revision_id?:string};
export type SchedulerData={self:{id:string;person_id:string;staff_id?:string;name:string;is_manager:boolean;is_ca:boolean;is_admin:boolean};week:{start:string;published_id:string|null;draft:Revision|null};people:Person[];published:{week:string;revision_id:string;shifts:WorkShift[]}[];jobs:TrainingPosition[];training:LinkedTraining[];signoffs:TrainingSignoff[];appointments:{id:string;scheduled_at:string;status:string;type:string;manager:string;employee:string}[];requests:ScheduleRequest[];announcements:Announcement[];announcement_history?:{id:number;announcement_id:string;at:string;value:Announcement}[];notifications:{id:string;body:string;created_at:string;read_at:string|null}[];accounts:{id:string;staff_id:string;active:boolean;is_ca:boolean;version:number}[];service:{email_verified?:boolean;email_evidence?:string;last_worker_at?:string};releases:{id:string;week:string;state:string;release_at:string;release_name:string;error:string}[];audit:{id:number;actor_name:string;action:string;record_id:string;changed_at:string;before_value:unknown;after_value:unknown}[]};
export type Act=(action:string,payload:Record<string,unknown>)=>Promise<Record<string,unknown>>;
export function shiftDay(iso:string){return new Intl.DateTimeFormat('sv-SE',{timeZone:zone}).format(new Date(iso))}
export function addDays(day:string,n:number){const d=new Date(day+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)}
export function weekOf(day=today()){return addDays(day,-new Date(day+'T12:00:00Z').getUTCDay())}
export function localFields(iso:string){const p=Object.fromEntries(new Intl.DateTimeFormat('en-US',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(iso)).map(x=>[x.type,x.value]));return `${p.year}-${p.month}-${p.day}T${p.hour}:${p.minute}`}
export function localCandidates(local:string){if(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(local))return [];return [5,6].map(offset=>new Date(Date.parse(local+':00Z')+offset*3600000).toISOString()).filter(iso=>localFields(iso)===local)}
export function centralInstant(local:string,occurrence=''){const candidates=localCandidates(local);if(!candidates.length)throw Error('That Central time does not exist. Choose another time.');if(candidates.length>1&&!['earlier','later'].includes(occurrence))throw Error('This time occurs twice when daylight saving ends. Choose the first or second occurrence.');return candidates[occurrence==='later'?candidates.length-1:0]}
export function clockTime(iso:string){return new Intl.DateTimeFormat('en-US',{timeZone:zone,hour:'numeric',minute:'2-digit'}).format(new Date(iso))}
export function hours(shifts:WorkShift[]){return Math.round(shifts.reduce((n,s)=>n+(Date.parse(s.end)-Date.parse(s.start))/3600000,0)*100)/100}
export function scheduleChanges(before:WorkShift[],after:WorkShift[]){return {added:after.filter(s=>!before.some(p=>p.id===s.id)),changed:after.filter(s=>before.some(p=>p.id===s.id&&['person_id','start','end','slot','job_id','qualification_reason'].some(k=>p[k as keyof WorkShift]!==s[k as keyof WorkShift]))),removed:before.filter(s=>!after.some(p=>p.id===s.id))}}
