import {SHLClassification} from './SHLClassification';
import {UsernameAccounts} from './UsernameAccounts';
import {useState} from 'react';
import {type SchedulerData,type Act} from './scheduler';
import {supabase} from './client';
import {displayTime} from './domain';
export function SchedulerAccounts({data,act,busy,reload,preview,auditOnly=false}:{data:SchedulerData;act:Act;busy:boolean;reload:()=>Promise<void>;preview:boolean;auditOnly?:boolean}){
 const [error,setError]=useState(''),[message,setMessage]=useState(''),[inviting,setInviting]=useState(false);
 const roleLabels:Record<string,string>={employee:'Employee',ca:'Community Ambassador',hSHL:'hSHL · Hourly leader',sSHL:'sSHL · Salaried manager',manager:'Unclassified manager',it:'IT Admin'};
 const accountRole=(a:SchedulerData['accounts'][number])=>a.role==='it'?'it':data.signoffs.filter(f=>f.staff_id===a.staff_id&&f.active).map(f=>data.jobs.find(j=>j.id===f.training_position_id)?.name).find(n=>n==='sSHL'||n==='hSHL')||a.role||(a.is_ca?'ca':'employee');
 async function run(action:string,p:Record<string,unknown>){setError('');try{await act(action,p);setMessage('Saved.')}catch(e){setError((e as Error).message)}}
 return <div className="scheduler-stack">{!auditOnly&&<><SHLClassification data={data} preview={preview} reload={reload}/><UsernameAccounts data={data} preview={preview} reload={reload}/><section className="panel scheduler-card"><h2>Account permissions</h2>{error&&<p className="error" role="alert">{error}</p>}{message&&<p className="success" role="status">{message}</p>}{data.accounts.map(a=><div className="person-row account-permission-row" key={a.id}><div className="grow"><strong>{data.people.find(p=>p.staff_id===a.staff_id)?.name}</strong><small>{roleLabels[accountRole(a)]} · {a.active?'Account active':'Account disabled'}</small></div>{data.self.is_admin&&<><select aria-label={'Account role for '+(data.people.find(p=>p.staff_id===a.staff_id)?.name||'employee')} value={accountRole(a)} disabled={busy||inviting||!a.active} onChange={async e=>{const role=e.target.value;const employee=data.people.find(p=>p.staff_id===a.staff_id)?.name||'this employee';if(!confirm('Change '+employee+' to '+roleLabels[role]+'? '+(role==='sSHL'?'This records sSHL qualification and grants schedule management.':role==='hSHL'?'This records hSHL qualification for office shifts without schedule management.':role==='it'?'This grants IT administration.':'This removes SHL qualifications and schedule management.')+' Their primary job, records and identity will be preserved.'))return;setError('');setInviting(true);try{if(preview)throw Error('Disconnected demo: role changes require a connected test account.');const r=await supabase!.rpc('set_employee_role',{p_id:a.id,p_role:role,p_version:a.version,p_manager_version:a.manager_version||0,p_submission:crypto.randomUUID()});if(r.error)throw r.error;await reload()}catch(err){setError((err as Error).message)}finally{setInviting(false)}}}><option value="employee">Employee</option><option value="ca">Community Ambassador</option><option value="hSHL">hSHL · Hourly leader</option><option value="sSHL">sSHL · Salaried manager</option>{accountRole(a)==='manager'&&<option value="manager" disabled>Unclassified manager — choose a category</option>}<option value="it">IT Admin</option></select><button disabled={busy} onClick={()=>void run('employee_access',{id:a.id,version:a.version,active:!a.active,is_ca:a.is_ca})}>{a.active?'Disable account':'Enable account'}</button></>}</div>)}</section>
 {data.self.is_admin&&<section className="panel scheduler-card"><h2>SHLs on the schedule</h2><p>Keep technical-only accounts off the work roster. This does not change their account permissions.</p>{data.people.filter(p=>p.group==='SHL').map(p=><div className="person-row" key={p.id}><strong className="grow">{p.name}</strong><button disabled={busy} onClick={()=>void run('roster',{id:p.id.slice(2),version:p.version,on_roster:!p.on_roster})}>{p.on_roster?'Remove from work roster':'Include on work roster'}</button></div>)}</section>}
 {data.self.is_admin&&<section className="panel scheduler-card"><h2>Optional email delivery</h2><p>Username accounts do not require this setup. Configure Resend with a verified domain in Supabase’s SMTP settings. Verify that both an invitation and a password reset reach the intended inbox before enabling invitations here.</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run('email_verified',{verified:f.has('verified'),evidence:f.get('evidence')})}}><label>Verification record<input name="evidence" defaultValue={data.service.email_evidence} placeholder="Verified sender, test date, invitation and reset results"/></label><label className="check"><input type="checkbox" name="verified" defaultChecked={data.service.email_verified}/>I verified invitation and password-reset delivery</label><button disabled={busy}>Save delivery status</button></form></section>}
 </>}<section className="panel scheduler-card"><h2>Schedule change history</h2>{data.audit.map(a=><details key={a.id}><summary>{displayTime(a.changed_at)} · {a.actor_name} · {a.action.replaceAll('_',' ')}</summary><div className="audit-values"><div><strong>Before</strong>{auditSummary(a.before_value,data)}</div><div><strong>After</strong>{auditSummary(a.after_value,data)}</div></div></details>)}{!data.audit.length&&<p>No schedule changes yet.</p>}</section></div>
}

function auditSummary(value:unknown,data:SchedulerData){
 if(!value)return <p>No earlier record.</p>;
 if(Array.isArray(value))return <p>{value.length} work shifts.</p>;
 const v=value as Record<string,unknown>;
 const name=(id:unknown)=>data.people.find(p=>p.id===id)?.name||'';
 return <div>{typeof v.state==='string'&&<p>{v.state==='Attention'?'Needs attention':v.state}</p>}{typeof v.status==='string'&&<p>{v.status}</p>}{Array.isArray(v.shifts)&&<p>{v.shifts.length} work shifts</p>}{typeof v.release_at==='string'&&<p>Release: {displayTime(v.release_at)}</p>}{typeof v.title==='string'&&<p>{v.title}</p>}{typeof v.body==='string'&&<p className="announcement-body">{v.body}</p>}{typeof v.reason==='string'&&<p>{v.reason}</p>}{typeof v.response==='string'&&<p>{v.response}</p>}{typeof v.person_id==='string'&&<p>{name(v.person_id)}</p>}{typeof v.is_ca==='boolean'&&<p>{v.is_ca?'CA access enabled':'Employee access'}</p>}{typeof v.active==='boolean'&&<p>{v.active?'Active':'Inactive'}</p>}</div>
}
