import {supabase} from './client';
import {PlanningSummary,Acknowledgment,localHours,hoursLabel,type Planning} from './Planning';
import {CoverageSettings} from './CoverageSettings';
import {ShiftTrade,type TradeKind} from './ShiftTrade';
import {ShiftMeetings} from './ShiftMeetings';
import {useEffect,useState} from 'react';
import {addDays,clockTime,hours,shiftDay,scheduleChanges,qualificationWarnings,shiftLabel,hourlyShifts,type SchedulerData,type WorkShift,type Act} from './scheduler';
import {DaySchedule,HoursBreakdown} from './DaySchedule';
import {visibleAssignments,categoryHours} from './scheduleDisplay';
import {displayTime,positionName} from './domain';
import {Modal,ShiftForm,CentralField,dateValue} from './SchedulerForms';
export function ScheduleBoard({data,week,setWeek,act,busy,onTraining,reload,preview}:{data:SchedulerData;week:string;setWeek:(w:string)=>void;act:Act;busy:boolean;onTraining:(revision?:string)=>void;reload:()=>Promise<void>;preview:boolean}){
 const [group,setGroup]=useState(''),[mode,setMode]=useState(data.self.is_manager?'team':'mine'),[editing,setEditing]=useState<{date:string;shift?:WorkShift;version:number}|null>(null),[review,setReview]=useState<{issues:string[];version:number;planning?:Planning}|null>(null),[error,setError]=useState(''),[issues,setIssues]=useState<string[]>([]),[releaseMode,setReleaseMode]=useState('now');
 const [meetingOpen,setMeetingOpen]=useState(false),[meetingBusy,setMeetingBusy]=useState(false);
 const draft=data.week.draft,manager=data.self.is_manager,published=data.published.find(p=>p.week===week)?.shifts||[],shifts=manager&&draft?draft.shifts:published;
 const editable=manager&&draft&&draft.state!=='Queued';
 const [planning,setPlanning]=useState<Planning|null>(null),[planningError,setPlanningError]=useState(''),[planningRefresh,setPlanningRefresh]=useState(0),[trade,setTrade]=useState<{shift:WorkShift;kind:TradeKind}|null>(null);
 const flags=manager?localHours(data,shifts,week):[];
 useEffect(()=>{let current=true;setPlanning(null);setPlanningError('');if(manager&&!preview)void supabase?.rpc('planning_read',{p_week:week,p_revision:draft?.id||null}).then(r=>{if(current){setPlanning(r.data);setPlanningError(r.error?.message||'')}});return()=>{current=false}},[manager,week,draft?.id,draft?.version,data.published,planningRefresh,preview]);

 const job=(s:WorkShift)=>shiftLabel(s,data.jobs);
 const outsideWeek=shifts.filter(s=>shiftDay(s.start)<week||shiftDay(s.start)>=addDays(week,7));
 const visible=visibleAssignments(shifts.filter(s=>!outsideWeek.some(x=>x.id===s.id)),data.jobs,group,mode==='mine'?data.self.person_id:null).filter(s=>mode!=='mine'||!!data.self.person_id);
 const roster=hourlyShifts(visible,data.people);
 const people=data.people.filter(p=>visible.some(s=>s.person_id===p.id));
 const office=visible.filter(s=>s.assignment_type==='opening_office'||s.assignment_type==='closing_office'||data.people.find(p=>p.id===s.person_id)?.employment_type==='Salaried');
 const editShift=(s:WorkShift)=>{if(draft){setError('');setEditing({date:shiftDay(s.start),shift:s,version:draft.version})}};
 const addShift=(day:string)=>{if(draft)setEditing({date:day,version:draft.version})};
 const name=(s:WorkShift)=>data.people.find(p=>p.id===s.person_id)?.name||'Former teammate';
 async function run(action:string,p:Record<string,unknown>){setError('');try{return await act(action,p)}catch(e){setError((e as Error).message);throw e}}
 async function save(shifts:WorkShift[]){if(!draft)return;if(editing&&editing.version!==draft.version){setError('This draft changed while the form was open. Close it and reopen the shift.');return}const result=await run('save',{id:draft.id,version:draft.version,shifts});setIssues((result.issues as string[])||[]);setEditing(null)}
 const changes=scheduleChanges(published,shifts);
 const warnings=manager?qualificationWarnings(data,shifts):[];
 const trainingWarnings=warnings.length>0&&<div className="warning" role="status"><strong>Training reminders</strong><ul>{warnings.map(w=><li key={w}>{w}</li>)}</ul><p>Assign a trainer if needed. These reminders do not block release.</p></div>;
 return <><section className="panel schedule-panel"><div className="schedule-controls"><div className="actions"><button aria-label="Previous week" onClick={()=>{setWeek(addDays(week,-7));setIssues([]);setError('')}}>←</button><h2>Week of {week}</h2><button aria-label="Next week" onClick={()=>{setWeek(addDays(week,7));setIssues([]);setError('')}}>→</button></div><div className="actions"><button aria-pressed={mode==='team'} onClick={()=>setMode('team')}>Team schedule</button><button aria-pressed={mode==='mine'} onClick={()=>setMode('mine')}>My schedule</button><button onClick={()=>window.print()}>Print week</button><select aria-label="Schedule position group" value={group} onChange={e=>setGroup(e.target.value)}><option value="">All positions</option>{['FOH','BOH','Catering','SHL','Training'].map(g=><option key={g} value={g}>{positionName(g)}</option>)}</select></div></div>
 <div className={'schedule-state '+(draft?.state==='Queued'?'purple':draft?'yellow':'blue')}><strong>{manager&&draft?draft.state==='Queued'?'Scheduled for release':draft.state==='Attention'?'Release needs attention':'Private draft':data.published.some(p=>p.week===week)?'Published schedule':'No schedule released yet'}</strong>{draft?.state==='Queued'?<span>{draft.release_at&&displayTime(draft.release_at)} Central · {draft.release_name} · Locked until release or cancellation</span>:<span>{draft?'Changes are saved privately. Employees still see the last release.':'Employees can see published work shifts. Meetings and training details stay personal.'}</span>}</div>
 {manager&&<div className="schedule-actions actions"><button onClick={()=>setMeetingOpen(true)} disabled={busy}>Shift check-ins</button>{!draft?<><button className="primary" disabled={busy} onClick={()=>void run('draft',{week}).catch(()=>{})}>Create draft</button><button disabled={busy} onClick={()=>void run('draft',{week,copy_previous:true}).catch(()=>{})}>Copy previous week</button></>:draft.state==='Queued'?<button disabled={busy} onClick={()=>{if(confirm('Cancel this queued release? The draft and published schedule will remain.'))void run('unqueue',{id:draft.id,version:draft.version}).catch(()=>{})}}>Cancel queued release</button>:<><button onClick={()=>setEditing({date:week,version:draft.version})} disabled={busy}>Add work shift</button><button disabled={busy} onClick={()=>onTraining(draft.id)}>Add draft training</button><button className="primary" disabled={busy} onClick={()=>void run('review',{id:draft.id,version:draft.version}).then(r=>{setReview({issues:r.issues as string[],version:draft.version,planning:preview?{hours:flags,coverage:[],missing:[{day:week,message:'Visual preview: coverage setup needed'}],requires_ack:true,fingerprint:'preview'}:r.planning as Planning});setReleaseMode('now')}).catch(()=>{})}>Review & release</button>{draft.base_id!==data.week.published_id&&<button disabled={busy} onClick={()=>{if(confirm('Replace this stale draft with the current published schedule? Draft work-shift edits will be preserved in change history.'))void run('rebase',{id:draft.id,version:draft.version}).catch(()=>{})}}>Reload published version</button>}</>}</div>}
 {(error||draft?.error)&&<p className="error" role="alert">{error||draft?.error}</p>}{issues.length>0&&<div className="error"><strong>Resolve before release</strong><ul>{issues.map((v,i)=><li key={i}>{v}</li>)}</ul></div>}
 {manager&&outsideWeek.length>0&&<section className="error" aria-label="Shifts outside this week"><h3>Shifts dated outside this week</h3><p>These assignments are saved with this schedule, but their dates fall outside {week} through {addDays(week,6)}. Correct the dates to place them on this board. They are excluded from this week’s hours.</p>{outsideWeek.map(s=><div className="actions" key={s.id}><span>{name(s)} · {job(s)} · {displayTime(s.start)}–{clockTime(s.end)}</span>{editable?<button disabled={busy} onClick={()=>editShift(s)}>Correct date / remove</button>:<span>{draft?.state==='Queued'?'Cancel the queued release to correct this shift.':'Create a draft to correct this shift.'}</span>}</div>)}</section>}
 {manager&&<><CoverageSettings preview={preview} week={week} data={data} onSaved={()=>{setPlanningRefresh(n=>n+1);void reload()}}/>{planningError&&<p className="error">Hours/coverage assessment unavailable: {planningError}</p>}{planning&&<PlanningSummary value={planning}/>}</>}{trainingWarnings}<DaySchedule data={data} week={week} shifts={roster} editable={!!editable} busy={busy} onEdit={editShift} onAdd={addShift} showAbsences group={group} mine={mode==='mine'} hoursFlags={flags} onRequest={(shift,kind)=>setTrade({shift,kind})}/>
 <section className="weekly-hours"><h3>Weekly hourly breakdown</h3><HoursBreakdown shifts={visible} data={data}/><p className="muted">Salaried assignments are excluded. Training is a separate category within the total.</p></section><details className="weekly-hours"><summary>Weekly hours by person</summary>{people.length?people.map(p=><p key={p.id}><strong>{p.name}</strong><span>{p.employment_type==='Salaried'?'Salaried · excluded from hourly totals':`${hours(visible.filter(s=>s.person_id===p.id))} filtered hours${manager?' · All jobs: '+hoursLabel(flags.find(h=>h.person_id===p.id)?.hours||0):''}`}</span></p>):<p>No scheduled employees match this view.</p>}</details><p className="panel-footer">Central time · {categoryHours(visible,data.people,data.jobs).Total} scheduled hourly hours · Planning totals, not payroll</p></section>
 <section className="panel office-schedule"><h2>Management & office</h2><p>All office coverage and salaried SHL work. Hourly office blocks also appear above and count once.</p><DaySchedule data={data} week={week} shifts={office} editable={!!editable} busy={busy} onEdit={editShift} onAdd={addShift} mine={mode==='mine'} hoursFlags={flags} onRequest={(shift,kind)=>setTrade({shift,kind})}/></section>
 {manager&&<section className="panel release-service"><h2>Release service</h2><p>Last successful check: {data.service.last_worker_at?displayTime(data.service.last_worker_at):'Not installed or not checked yet'}</p>{data.service.last_worker_at&&Date.now()-Date.parse(data.service.last_worker_at)>180000&&<p className="error">The release service has not checked recently. An IT Admin should inspect the scheduled job.</p>}{data.releases.map(r=><p key={r.id}><strong>{r.week} · {r.state==='Queued'?'Scheduled for release':'Needs attention'}</strong> {r.release_at&&displayTime(r.release_at)} · {r.release_name}{r.error&&<span className="error">{r.error}</span>}</p>)}</section>}
 {editing&&<Modal title={draft?.shifts.some(s=>s.id===editing.shift?.id)?'Edit work shift':'Add work shift'} busy={busy} onClose={()=>{setEditing(null);setError('')}}><>{manager&&<p className="notice">35+ hours require acknowledgment at release. Current totals across all jobs: {flags.filter(h=>h.hours>=35).map(h=>h.name+' '+hoursLabel(h.hours)).join('; ')||'No employees at 35+ hours.'}</p>}<ShiftForm data={data} shift={editing.shift} date={editing.date} busy={busy} error={error} onSave={s=>save([...shifts.filter(p=>p.id!==s.id),s]).catch(()=>{})}/></>{editing.shift&&draft?.shifts.some(s=>s.id===editing.shift?.id)&&<button className="danger-text" disabled={busy} onClick={()=>{if(confirm('Remove this shift from the draft? The published schedule stays unchanged until release.'))void save(shifts.filter(s=>s.id!==editing.shift?.id)).catch(()=>{})}}>Remove from draft</button>}</Modal>}
 {meetingOpen&&<Modal title="Meetings during shifts" busy={meetingBusy} onClose={()=>setMeetingOpen(false)}><ShiftMeetings data={data} preview={preview} reload={reload} onBusy={setMeetingBusy}/></Modal>}
 {trade&&<ShiftTrade shift={trade.shift} kind={trade.kind} data={data} act={act} busy={busy} onClose={()=>setTrade(null)}/>}{review&&draft&&<Modal title="Review schedule release" busy={busy} onClose={()=>{setReview(null);setError('')}}>{review.version!==draft.version&&<p className="error">The draft changed after this review. Close this window and review it again.</p>}<p>Week of {week} · {changes.added.length} added · {changes.changed.length} changed · {changes.removed.length} cancelled</p>{(['added','changed','removed'] as const).map(kind=>changes[kind].length>0&&<section key={kind}><h3>{kind==='removed'?'Cancelled':kind[0].toUpperCase()+kind.slice(1)}</h3>{changes[kind].map(s=><p key={s.id}>{name(s)} · {displayTime(s.start)}–{clockTime(s.end)} · {job(s)}</p>)}</section>)}{trainingWarnings}<h3>Associated check-ins</h3>{data.shift_meetings?.filter(m=>m.status==='Scheduled'&&shifts.some(s=>s.id===m.work_shift_id)).map(m=><p key={m.id}>{m.employee} · Meeting with {m.manager} during assigned shift</p>)}<h3>Associated training</h3>{data.training.filter(t=>t.schedule_revision_id===draft.id||shifts.some(s=>s.id===t.work_shift_id)).map(t=><p key={t.id}>{data.people.find(p=>p.staff_id===t.staff_id)?.name} · {displayTime(t.scheduled_at)} · {t.status}</p>)}{review.issues.length>0?<div className="error"><strong>Fix these issues before release</strong><ul>{review.issues.map((s,i)=><li key={i}>{s}</li>)}</ul></div>:<p className="success">Current checks passed. The server checks again when releasing.</p>}<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const payload:Record<string,unknown>={id:draft.id,version:review.version,fingerprint:f.get('fingerprint'),acknowledged:f.get('acknowledged')==='on',review_reason:f.get('review_reason')||''};if(releaseMode==='later')payload.release_at=dateValue(f,'release');void run(releaseMode==='later'?'queue':'release',payload).then(()=>setReview(null)).catch(()=>{})}catch(err){setError((err as Error).message)}}}>{review.planning?<><PlanningSummary value={review.planning}/><Acknowledgment value={review.planning}/></>:<p className="error">Hours and coverage review is unavailable. Refresh after the database update is installed.</p>}<label>Release timing<select value={releaseMode} onChange={e=>setReleaseMode(e.target.value)}><option value="now">Release now</option><option value="later">Choose a release date and time</option></select></label>{releaseMode==='later'&&<><CentralField name="release" label="Release at (Central)" value={week+'T09:00'}/><p className="muted">This locks the reviewed schedule. Cancel the queued release before making further edits.</p></>}{error&&<p role="alert" className="error">{error}</p>}<button className="primary" disabled={busy||!review.planning||review.issues.length>0||review.version!==draft.version}>{busy?'Saving…':releaseMode==='later'?'Lock & schedule release':'Release schedule now'}</button></form></Modal>}</>
}
