import {useEffect,useState,useRef} from 'react';
import {supabase} from './client';
import type {SchedulerData,WorkShift} from './scheduler';
import {Modal} from './SchedulerForms';
export type ShiftPreset={id:string;name:string;job_id:string|null;assignment_type:NonNullable<WorkShift['assignment_type']>;start_time:string;end_time:string;next_day:boolean;active:boolean;version:number};
export function ShiftPresets({data,onApply,preview=false}:{data:SchedulerData;onApply:(preset:ShiftPreset)=>void;preview?:boolean}){
 const [rows,setRows]=useState<ShiftPreset[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[editing,setEditing]=useState<ShiftPreset|null|undefined>(),[notice,setNotice]=useState('');const retry=useRef<{key:string;id:string}|undefined>(undefined);
 async function load(){setLoading(true);if(preview){setRows([{id:'example',name:'Lunch GSR',job_id:data.jobs.find(j=>j.name==='GSR')?.id||null,assignment_type:'regular',start_time:'11:00',end_time:'16:00',next_day:false,active:true,version:1}]);setLoading(false);return}const r=await supabase!.rpc('shift_presets_read');setError(r.error?'Shift presets unavailable. '+r.error.message:'');if(!r.error)setRows(r.data);setLoading(false)}
 useEffect(()=>{void load()},[]);
 async function save(payload:Record<string,unknown>){setBusy(true);setError('');try{if(preview)throw Error('Preset changes are unavailable in the disconnected preview.');const key=JSON.stringify(payload);if(retry.current?.key!==key)retry.current={key,id:crypto.randomUUID()};const r=await supabase!.rpc('shift_preset_save',{p_payload:payload,p_submission:retry.current.id});if(r.error)throw r.error;retry.current=undefined;setEditing(undefined);setNotice('Preset saved. Existing shifts are unchanged.');await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <details className="shift-presets"><summary>Shift presets</summary><p>Fill this form from a reusable pattern, then choose the person and review before saving.</p>{loading?<p>Loading presets…</p>:<div className="actions">{rows.filter(p=>p.active).map(p=><button type="button" key={p.id} disabled={busy||!!p.job_id&&!data.jobs.some(j=>j.id===p.job_id&&j.active)} onClick={()=>onApply(p)}>Use {p.name}</button>)}</div>}{!loading&&!rows.some(p=>p.active)&&!error&&<p>No presets yet.</p>}<button type="button" onClick={()=>setEditing(null)}>New preset</button>{rows.filter(p=>p.active).map(p=><button type="button" key={p.id} onClick={()=>setEditing(p)}>Edit {p.name}</button>)}{notice&&<p role="status">{notice}</p>}{error&&<p role="alert" className="error">{error}</p>}{editing!==undefined&&<Modal title={editing?'Edit shift preset':'New shift preset'} busy={busy} onClose={()=>setEditing(undefined)}><form onSubmit={e=>{e.preventDefault();e.stopPropagation();const f=new FormData(e.currentTarget);const kind=String(f.get('assignment_type'));void save({id:editing?.id,version:editing?.version,name:f.get('name'),job_id:kind==='regular'?f.get('job_id')||null:null,assignment_type:kind,start_time:f.get('start_time'),end_time:f.get('end_time'),next_day:f.has('next_day')})}}><fieldset disabled={busy}><label>Name<input name="name" required maxLength={80} defaultValue={editing?.name}/></label><label>Assignment<select name="assignment_type" defaultValue={editing?.assignment_type||'regular'}><option value="regular">Regular work</option><option value="training">Dedicated Training</option><option value="opening_office">Opening office</option><option value="closing_office">Closing office</option></select></label><label>Job (regular work only)<select name="job_id" defaultValue={editing?.job_id||''}><option value="">General SHL duty / no regular job</option>{data.jobs.filter(j=>j.active).map(j=><option value={j.id} key={j.id}>{j.name}</option>)}</select></label><label>Start (Central)<input type="time" name="start_time" required defaultValue={editing?.start_time.slice(0,5)||'11:00'}/></label><label>End (Central)<input type="time" name="end_time" required defaultValue={editing?.end_time.slice(0,5)||'16:00'}/></label><label className="check"><input type="checkbox" name="next_day" defaultChecked={editing?.next_day}/>Ends the next day</label><button className="primary">Save preset</button>{editing&&<button type="button" onClick={()=>{if(confirm('Archive this preset? Existing shifts remain unchanged.'))void save({id:editing.id,version:editing.version,archive:true})}}>Archive preset</button>}</fieldset></form></Modal>}</details>;
}
