import {useEffect,useState} from 'react';
import {supabase} from './client';
import {Modal} from './SchedulerForms';
import {clockTime,shiftLabel,type Act,type SchedulerData,type WorkShift} from './scheduler';
import {displayTime} from './domain';
export type TradeKind='Trade'|'Coverage'|'Offer';
export function ShiftTrade({shift,kind,data,act,busy,onClose}:{shift:WorkShift;kind:TradeKind;data:SchedulerData;act:Act;busy:boolean;onClose:()=>void}){
 const [options,setOptions]=useState<{people:{id:string;name:string}[];trades:WorkShift[]}|null>(null),[error,setError]=useState('');
 useEffect(()=>{let current=true;void supabase?.rpc('trade_options',{p_shift:shift.id}).then(r=>{if(current){setError(r.error?.message||'');setOptions(r.data)}});return()=>{current=false}},[shift.id]);
 return <Modal title={kind==='Trade'?'Trade shift':kind==='Coverage'?'Ask coworker to cover':'Offer shift'} busy={busy} onClose={onClose}><p><strong>{shiftLabel(shift,data.jobs)}</strong> · {displayTime(shift.start)}–{clockTime(shift.end)} · {((Date.parse(shift.end)-Date.parse(shift.start))/3600000).toFixed(2)}h</p>{error&&<p className="error" role="alert">{error}</p>}{!options&&!error&&<p>Checking eligible coworkers…</p>}{options&&<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act('request',{kind,source_id:shift.id,target_id:f.get('target')||null,recipient:f.get('recipient')||null,reason:f.get('reason')||''}).then(onClose).catch(e=>setError(e.message))}}><fieldset disabled={busy}>{kind==='Coverage'&&<label>Coworker<select name="recipient" required defaultValue=""><option value="">Choose eligible coworker</option>{options.people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>}{kind==='Trade'&&<label>Shift in return<select name="target" required defaultValue=""><option value="">Choose eligible shift</option>{options.trades.map(s=><option key={s.id} value={s.id}>{data.people.find(p=>p.id===s.person_id)?.name} · {shiftLabel(s,data.jobs)} · {displayTime(s.start)}–{clockTime(s.end)}</option>)}</select></label>}{kind!=='Offer'&&!(kind==='Trade'?options.trades:options.people).length?<p className="notice">No eligible matches right now. Ask your manager for help.</p>:<><label>Private reason (optional)<textarea name="reason" maxLength={2000}/></label><p>A coworker must accept before a manager can approve. Your assignment stays unchanged until approval.</p><button className="primary">{kind==='Offer'?'Offer to eligible coworkers':'Send request'}</button></>}</fieldset></form>}</Modal>
}
