import {hourlyShifts,shiftLabel} from './scheduler';
import {CalendarDays,ClipboardCheck,ShieldCheck,Users,ArrowRight,BookOpen,Clock,Activity} from 'lucide-react';
import {type SchedulerData,type Workspace,hours,shiftDay,clockTime,addDays} from './scheduler';
import {today,displayTime,positionName} from './domain';
import {Operations} from './Operations';
import {trainingProgress} from './trainingProgress';
export function WorkspaceHome({data,workspace,go,preview}:{data:SchedulerData;workspace:Workspace;go:(page:string)=>void;preview:boolean}){
 const day=today(),all=data.published.flatMap(w=>w.shifts),todayShifts=all.filter(s=>shiftDay(s.start)===day).sort((a,b)=>a.start.localeCompare(b.start)),own=all.filter(s=>s.person_id===data.self.person_id&&Date.parse(s.end)>Date.now()).sort((a,b)=>a.start.localeCompare(b.start));
 const name=(id:string)=>data.people.find(p=>p.id===id)?.name||'Former teammate';
 const pending=data.requests.filter(q=>['Pending','Accepted'].includes(q.status));
 const unread=data.notifications.filter(n=>!n.read_at).length+data.announcements.filter(a=>a.active&&!a.read).length;
 if(workspace==='employee')return <div className="employee-home"><section className="next-shift"><span className="eyebrow">YOUR NEXT SHIFT</span>{own[0]?<><h2>{displayTime(own[0].start)}</h2><p>{clockTime(own[0].start)}–{clockTime(own[0].end)} · {shiftLabel(own[0],data.jobs)} · Shift {own[0].slot}</p></>:<><h2>You’re up to date.</h2><p>No upcoming published shifts assigned.</p></>}<button onClick={()=>go('schedule')}>View my schedule <ArrowRight size={17}/></button></section><div className="home-metrics"><button onClick={()=>go('requests')}><ClipboardCheck/><strong>{pending.filter(q=>q.created_by===data.self.id).length}</strong><span>Requests waiting</span></button><button onClick={()=>go('announcements')}><BookOpen/><strong>{unread}</strong><span>Unread updates</span></button></div><Commitments data={data}/><section className="panel scheduler-card"><h2>Your training journey</h2>{data.jobs.filter(j=>data.signoffs.some(f=>f.active&&f.staff_id===data.self.staff_id&&f.training_position_id===j.id)||data.training.some(t=>t.staff_id===data.self.staff_id&&t.training_position_id===j.id)||data.people.some(p=>p.id===data.self.person_id&&p.primary_job_id===j.id)).map(j=>{const p=trainingProgress(data.self.staff_id||'',j,data.training,data.signoffs);return <p key={j.id}><strong>{j.name}</strong> · {p.completed}/{p.target} completed shifts · {data.signoffs.some(s=>s.staff_id===data.self.staff_id&&s.training_position_id===j.id&&s.active)?'Signed off':p.remaining?p.remaining+' shifts remaining':'Ready for manager sign-off'}</p>})}<button onClick={()=>go('training')}>{data.self.is_ca?'Open team training tools':'View training progress'}</button></section>{data.self.is_ca&&<section className="ca-tools"><h2>Community Ambassador tools</h2><p>Help the team learn and stay informed.</p><div className="actions"><button onClick={()=>go('training')}>Schedule training</button><button onClick={()=>go('announcements')}>Publish announcement</button></div></section>}{!data.people.some(p=>p.id===data.self.person_id&&p.on_roster)&&<p className="notice">Your account is not linked to a rostered person. Personal shifts and requests are unavailable until IT updates the link.</p>}</div>;
 if(workspace==='it')return <div className="it-home"><WorkspaceHome data={data} workspace="manager" go={go} preview={preview}/><section className="system-heading"><ShieldCheck size={34}/><div><h2>Access. Reliability. Accountability.</h2><p>Daily operations and administration for Downers Grove.</p></div></section><div className="home-metrics"><button onClick={()=>go('accounts')}><Users/><strong>{data.accounts.filter(a=>a.active).length}</strong><span>Active employee accounts</span></button><button onClick={()=>go('accounts')}><ShieldCheck/><strong>Username</strong><span>Create an account</span></button><button onClick={()=>go('settings')}><Activity/><strong>{data.service.last_worker_at&&Date.now()-Date.parse(data.service.last_worker_at)<180000?'Healthy':'Check'}</strong><span>Release service</span></button></div><section className="panel scheduler-card"><h2>System checks</h2><dl className="system-checks"><dt>Release worker</dt><dd>{data.service.last_worker_at?'Last check '+displayTime(data.service.last_worker_at):'No successful check recorded'}</dd><dt>Authentication email</dt><dd>{data.service.email_verified?'Delivery verified':'Optional email delivery is not configured. Username accounts do not require email.'}</dd><dt>Permission model</dt><dd>Server-enforced access · Creator-only meeting and training edits</dd><dt>Location timezone</dt><dd>America/Chicago</dd></dl></section><ReleaseAttention data={data} go={go}/><section className="panel scheduler-card"><h2>Recent administrative activity</h2>{data.audit.slice(0,6).map(a=><p key={a.id}>{a.actor_name} · {a.action.replaceAll('_',' ')} <small>{displayTime(a.changed_at)}</small></p>)}{!data.audit.length&&<p className="muted">No changes recorded yet.</p>}<button onClick={()=>go('audit')}>Open change history</button></section></div>;
 const absences=data.requests.filter(q=>q.kind==='Time off'&&q.status==='Approved'&&shiftDay(q.payload.start!)<=day&&shiftDay(q.payload.end!)>=day);
 return <div className="manager-home"><div className="actions"><button onClick={()=>go('directory')}>Find a teammate</button><button onClick={()=>go('oneOnOnes')}>{data.meeting_due?.length||0} upcoming shifts needing a 1:1</button></div><div className="home-metrics"><button onClick={()=>go('schedule')}><Users/><strong>{new Set(todayShifts.map(s=>s.person_id)).size}</strong><span>People scheduled today</span></button><button onClick={()=>go('requests')}><ClipboardCheck/><strong>{pending.length}</strong><span>Requests to review</span></button><button onClick={()=>go('training')}><BookOpen/><strong>{data.training.filter(t=>t.status==='Scheduled'&&shiftDay(t.scheduled_at)===day).length}</strong><span>Training sessions today</span></button><button onClick={()=>go('schedule')}><Clock/><strong>{hours(hourlyShifts(todayShifts,data.people))}</strong><span>Scheduled hours today</span></button></div><ReleaseAttention data={data} go={go}/><div className="brief-columns"><section className="panel scheduler-card"><div className="section-title"><h2>Today’s staffing</h2><button onClick={()=>window.print()}>Print daily brief</button></div>{todayShifts.map(s=><div className="brief-row" key={s.id}><div><strong>{name(s.person_id)}</strong><small>{shiftLabel(s,data.jobs)} · Shift {s.slot}</small></div><span>{clockTime(s.start)}–{clockTime(s.end)}</span></div>)}{!todayShifts.length&&<p className="muted">No published shifts for today.</p>}<button onClick={()=>go('schedule')}>Open schedule builder</button></section><section className="panel scheduler-card"><h2>Approved absences</h2>{absences.map(q=><div className="brief-row" key={q.id}><strong>{name(q.person_id)}</strong><span>{q.payload.category||'Time off'} · {displayTime(q.payload.start!)}</span></div>)}{!absences.length&&<p className="muted">No approved absences for today.</p>}<h2>Pending decisions</h2>{pending.slice(0,5).map(q=><p key={q.id}><button onClick={()=>go('requests?request='+encodeURIComponent(q.id))}>{name(q.person_id)} · {q.payload.category||q.kind}</button></p>)}{!pending.length&&<p className="muted">All caught up.</p>}<button onClick={()=>go('requests')}>Review requests</button></section></div><Operations page="brief" workspace={workspace} data={data} preview={preview}/></div>;
}
export function Commitments({data}:{data:SchedulerData}){const meetings=data.appointments.filter(a=>a.status==='Scheduled').sort((a,b)=>a.scheduled_at.localeCompare(b.scheduled_at)),training=data.training.filter(t=>t.status==='Scheduled'&&(t.staff_id===data.self.staff_id||t.trainer_id===data.self.staff_id)).sort((a,b)=>a.scheduled_at.localeCompare(b.scheduled_at));return <section className="panel scheduler-card"><h2>Your meetings & training</h2>{meetings.map(m=><p key={m.id}><strong>{m.type} meeting · {m.employee}</strong><br/>{displayTime(m.scheduled_at)} · {m.manager}</p>)}{training.map(t=><p key={t.id}><strong>{data.people.find(p=>p.staff_id===t.trainer_id)?.name} Training {data.people.find(p=>p.staff_id===t.staff_id)?.name}</strong><br/>{displayTime(t.scheduled_at)}</p>)}{!meetings.length&&!training.length&&<p className="muted">No upcoming meetings or training assignments.</p>}</section>}
function ReleaseAttention({data,go}:{data:SchedulerData;go:(p:string)=>void}){return data.releases.length?<section className="panel scheduler-card"><h2>Schedule releases</h2>{data.releases.map(r=><div className="release-summary" key={r.id}><span className={'chip '+(r.state==='Queued'?'purple':'orange')}>{r.state==='Queued'?'Scheduled for release':'Needs attention'}</span><p>Week of {r.week} · {r.release_name}{r.release_at?' · '+displayTime(r.release_at):''}</p>{r.error&&<p className="error">{r.error}</p>}<button onClick={()=>go('schedule?week='+r.week)}>Review this week</button></div>)}</section>:null}
