import {useCallback,useEffect,useRef,useState,type ReactNode} from 'react';
import type {Session} from '@supabase/supabase-js';
import {CalendarDays,Users,MessageSquare,BookOpen,LogOut,RefreshCw,ShieldCheck,ClipboardList,ArrowLeft,Clock} from 'lucide-react';
import {supabase,configured} from './client';
import {LoginForm,PasswordForm} from './AuthForms';
import {ScheduleBoard} from './ScheduleBoard';
import {ScheduleRequests} from './ScheduleRequests';
import {Announcements} from './Announcements';
import {SchedulerAccounts} from './SchedulerAccounts';
import {SchedulerTraining} from './SchedulerTraining';
import {type SchedulerData,type Act,type LinkedTraining,type ScheduleRequest,weekOf,addDays,centralInstant,localFields} from './scheduler';
import {Modal,TrainingForm} from './SchedulerForms';
import {displayTime,today} from './domain';
import {approvedAvailability} from './availability';
import './scheduler.css';
const preview=import.meta.env.DEV&&new URLSearchParams(location.search).get('preview')==='1';
function demo(week:string,role:string,requests:ScheduleRequest[]=[]):SchedulerData{
 const people=[{id:'s:Alex.L',staff_id:'Alex.L',name:'Alex Lane',group:'FOH',active:true,on_roster:true,is_trainer:true,is_ca:true,primary_job_id:'gsr'},{id:'s:Casey.W',staff_id:'Casey.W',name:'Casey Williams',group:'FOH',active:true,on_roster:true,is_trainer:false,primary_job_id:'gsr'},{id:'s:Jordan.D',staff_id:'Jordan.D',name:'Jordan Davis',group:'BOH',active:true,on_roster:true,is_trainer:false},{id:'m:demo',name:'Morgan Hayes',group:'SHL',active:true,on_roster:true,is_trainer:false}];
 const shifts=people.flatMap((p,i)=>[1,3,5].map((d,j)=>({id:`demo-${i}-${d}`,person_id:p.id,start:centralInstant(addDays(week,d)+'T'+(j===1?'14:00':'11:00')),end:centralInstant(addDays(week,d)+'T'+(j===1?'21:00':'17:00')),slot:j===1?2:1,job_id:p.group==='SHL'?null:p.group==='BOH'?'line':'gsr',qualification_reason:'Supervised learning'})));
 return {self:{id:role==='manager'?'demo':role==='ca'?'ca':'employee',person_id:role==='manager'?'m:demo':role==='ca'?'s:Alex.L':'s:Casey.W',staff_id:role==='manager'?undefined:role==='ca'?'Alex.L':'Casey.W',name:role==='manager'?'Morgan Hayes':role==='ca'?'Alex Lane':'Casey Williams',is_manager:role==='manager',is_ca:role==='ca',is_admin:role==='manager'},week:{start:week,published_id:'demo-published',draft:null},people,published:[{week,revision_id:'demo-published',shifts}],jobs:[{id:'gsr',name:'GSR',department:'FOH',active:true,target_shifts:4},{id:'expo',name:'EXPO',department:'FOH',active:true,target_shifts:4},{id:'drl',name:'DRL',department:'FOH',active:true,target_shifts:4},{id:'line',name:'Line',department:'BOH',active:true,target_shifts:4},{id:'prep',name:'Prep',department:'BOH',active:true,target_shifts:4},{id:'catering',name:'Catering',department:'Catering',active:true,target_shifts:4}],training:[{id:'demo-training',staff_id:'Casey.W',trainer_id:'Alex.L',training_position_id:'gsr',scheduled_at:centralInstant(addDays(week,1)+'T11:00'),ends_at:centralInstant(addDays(week,1)+'T15:00'),shift:1,status:'Scheduled',version:1,created_by:'demo',work_shift_id:'demo-1-1',trainer_shift_id:'demo-0-1'}],signoffs:[],appointments:[],requests:requests.filter(q=>role==='manager'||q.created_by===(role==='ca'?'ca':'employee')),announcements:[{id:'demo-announcement',title:'Ready for a great week.',body:'Check your schedule and training assignments. Submit any availability changes through Requests so your managers can review them.',groups:[],created_by:'demo',author:'Morgan Hayes',active:true,version:1,created_at:new Date().toISOString(),read:false}],notifications:[],accounts:[],service:{email_verified:false,last_worker_at:new Date().toISOString()},releases:[],audit:[]};
}
export function WorkspaceRoot({legacy}:{legacy:(back:(view?:string)=>void,authors:Record<string,string>)=>ReactNode}){
 const [session,setSession]=useState<Session|null>(null),[checking,setChecking]=useState(!preview),[week,setWeek]=useState(weekOf()),[role,setRole]=useState('manager'),[data,setData]=useState<SchedulerData|null>(preview?demo(weekOf(),'manager'):null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[view,setView]=useState('schedule'),[old,setOld]=useState(false),[password,setPassword]=useState(()=>['recovery','invite'].includes(new URLSearchParams(location.hash.slice(1)).get('type')||'')),[training,setTraining]=useState<{revision?:string;initial?:LinkedTraining}|null>(null);
 const previewRequests=useRef<ScheduleRequest[]>([{id:'demo-approved-hours',kind:'Availability',person_id:'s:Casey.W',created_by:'employee',status:'Approved',version:2,created_at:addDays(today(),-15)+'T12:00:00Z',decided_at:addDays(today(),-14)+'T12:00:00Z',decided_name:'Morgan Hayes',payload:{effective:addDays(today(),-14),days:Array.from({length:7},(_,i)=>i===0?[[690,1200]]:[[660,1260]])}}]);
 const serial=useRef(0),pending=useRef<{key:string;id:string}|null>(null),sessionId=useRef<string|undefined>(undefined);
 const load=useCallback(async()=>{if(preview)return;const token=++serial.current;if(!supabase||!session)return;const {data:r,error:e}=await supabase.rpc('scheduler_read',{p_week:week});if(token!==serial.current)return;if(e){setData(null);setError(e.message);throw Error(e.message)}setData(r as SchedulerData);setError('')},[session?.user.id,week]);
 useEffect(()=>{if(preview){setChecking(false);return}if(!supabase){setChecking(false);return}supabase.auth.getSession().then(({data})=>{sessionId.current=data.session?.user.id;setSession(data.session);setChecking(false)});const {data:l}=supabase.auth.onAuthStateChange((event,s)=>{if(event==='PASSWORD_RECOVERY')setPassword(true);if(sessionId.current!==s?.user.id){serial.current++;setData(null);setOld(false);setTraining(null);setError('');pending.current=null}sessionId.current=s?.user.id;setSession(s)});return()=>l.subscription.unsubscribe()},[]);
 useEffect(()=>{if(preview){setData(demo(week,role,previewRequests.current));return}if(session)void load().catch(()=>{})},[session?.user.id,week,role,load]);
 useEffect(()=>{if(!session||preview)return;const refresh=()=>{if(document.visibilityState==='visible')void load().catch(()=>{})};window.addEventListener('focus',refresh);const timer=setInterval(refresh,60000);return()=>{clearInterval(timer);window.removeEventListener('focus',refresh)}},[load,session]);
 async function signOut(){await supabase?.auth.signOut();setData(null);setSession(null);setOld(false);setPassword(false)}
 const act:Act=async(action,payload)=>{if(busy)throw Error('A save is already in progress.');setBusy(true);setError('');setNotice('');try{if(preview){setNotice('Disconnected preview: no live records changed.');
 if(data&&(action==='request'&&payload.kind==='Availability'||['decide','withdraw','revoke'].includes(action)&&previewRequests.current.some(q=>q.id===payload.id))){
  let requests=previewRequests.current;
  if(action==='request')requests=[{id:crypto.randomUUID(),kind:'Availability',person_id:data.self.person_id,created_by:data.self.id,status:'Pending',version:1,created_at:new Date().toISOString(),payload:payload.details as ScheduleRequest['payload'],reason:String(payload.reason||'')},...requests];
  else {
   const q=requests.find(q=>q.id===payload.id)!;
   if(q.version!==payload.version)throw Error('This request changed. Reload.');
   if(action==='withdraw'?q.created_by!==data.self.id:!data.self.is_manager||q.created_by===data.self.id)throw Error('Another manager must decide this request.');
   requests=requests.map(q=>q.id===payload.id?{...q,status:action==='withdraw'||action==='revoke'?'Withdrawn':String(payload.decision),version:q.version+1,...(action==='withdraw'?{}:{response:String(payload.response||''),decided_at:new Date().toISOString(),decided_name:data.self.name})}:q);
   if(action==='decide'&&payload.decision==='Approved'||action==='revoke'){
    for(const shift of data.published.flatMap(w=>w.shifts).filter(s=>s.person_id===q.person_id&&new Date(s.end)>new Date())){
     const start=localFields(shift.start),end=localFields(shift.end);
     for(let day=start.slice(0,10);day<=end.slice(0,10);day=addDays(day,1)){
      const lo=day===start.slice(0,10)?Number(start.slice(11,13))*60+Number(start.slice(14)):0,hi=day===end.slice(0,10)?Number(end.slice(11,13))*60+Number(end.slice(14)):1440;
      const approved=approvedAvailability(requests,q.person_id,day);
      let coveredTo=lo;for(const [a,b] of approved?.payload.days?.[new Date(day+'T12:00:00Z').getUTCDay()]||[]){if(a<=coveredTo&&b>coveredTo)coveredTo=b}
      if(hi>lo&&approved&&coveredTo<hi)throw Error('Resolve conflicting published shifts before approving: '+day);
     }
    }
   }
  }
  previewRequests.current=requests;setData({...data,requests:requests.filter(q=>data.self.is_manager||q.created_by===data.self.id)});return {};
 }
 if(action==='draft'&&data){setData({...data,week:{...data.week,draft:{id:'demo-draft',version:1,state:'Draft',base_id:data.week.published_id,shifts:data.published.find(p=>p.week===week)?.shifts||[],release_at:null,release_name:'Morgan Hayes',error:null}}})}else if(data?.week.draft&&['save','queue','unqueue','release'].includes(action)){const d=data.week.draft;if(action==='release')setData({...data,published:[...data.published.filter(p=>p.week!==week),{week,revision_id:d.id,shifts:d.shifts}],week:{...data.week,draft:null,published_id:d.id}});else setData({...data,week:{...data.week,draft:{...d,version:d.version+1,shifts:action==='save'?payload.shifts as typeof d.shifts:d.shifts,state:action==='queue'?'Queued':'Draft',release_at:action==='queue'?String(payload.release_at):null}}})}return {issues:[],state:action==='release'?'Published':'Draft'}}const key=JSON.stringify([action,payload]);if(pending.current?.key!==key)pending.current={key,id:crypto.randomUUID()};const {data:result,error:e}=await supabase!.rpc('scheduler_action',{p_action:action,p_payload:payload,p_submission:pending.current.id});if(e)throw Error(e.message);pending.current=null;setNotice(result.state==='Attention'?'Saved; release needs attention.':'Saved.');try{await load()}catch{setNotice('Saved; the workspace needs refreshing. Do not submit again.')}return result}catch(e){setError((e as Error).message);throw e}finally{setBusy(false)}};
 if(checking)return <div className="loading">Opening your workspace…</div>;
 if(!session&&!preview)return <div className="login"><div className="login-story"><div className="brand"><span className="brand-icon">M</span><span>MISSION BBQ<small>TEAM WORKSPACE</small></span></div><div><p className="eyebrow">TOGETHER, EVERY SHIFT</p><h1>Your team.<br/>Your next shift.</h1><p>Schedules, training, and the conversations that keep us connected.</p></div><small>Private access for your restaurant team.</small></div><section className="login-form"><p className="eyebrow">TEAM WORKSPACE</p><h2>Welcome back.</h2><p className="muted">Sign in with your approved email and password.</p>{configured?<LoginForm/>:<p>The workspace is being connected.</p>}</section></div>;
 if(session&&password)return <PasswordForm email={session.user.email||''} onClose={()=>setPassword(false)} onSaved={()=>{setPassword(false);setNotice('Password saved.')}}/>;
 if(!data)return <div className="loading"><ShieldCheck/><h2>{error?'Workspace needs attention':'Opening your workspace…'}</h2><p>{error}</p><button onClick={()=>void load().catch(()=>{})}>Refresh</button><button onClick={()=>void signOut()}>Sign out</button></div>;
 if(old&&data.self.is_manager)return legacy(next=>{setView(next||'schedule');setOld(false);void load().catch(()=>{})},Object.fromEntries(data.accounts.map(a=>[a.id,data.people.find(p=>p.staff_id===a.staff_id)?.name||'Former teammate'])));
 const titles:Record<string,string>={schedule:'The week ahead.',requests:'Make a plan that works.',availability:'When you can work.',training:'Build skills. Grow together.',announcements:'Stay in the loop.',accounts:'Your team’s access.'};
 const unread=data.announcements.filter(a=>a.active&&!a.read).length+data.notifications.filter(n=>!n.read_at).length;
 return <div className="shell scheduler-shell"><aside><div className="brand"><span className="brand-icon">M</span><span>MISSION BBQ<small>TEAM WORKSPACE</small></span></div><p className="nav-label">YOUR WORKSPACE</p><nav>{([['schedule','Schedule',CalendarDays],['availability','Availability',Clock],['requests','Requests',ClipboardList],['training','Training',BookOpen],['announcements','Announcements',MessageSquare]] as const).map(([id,title,Icon])=><button key={id} className={view===id?'selected':''} onClick={()=>{setView(id);setNotice('');setError('')}}><Icon size={18}/>{title}{id==='announcements'&&unread>0&&<span className="nav-count">{unread}</span>}</button>)}{data.self.is_manager&&<><button onClick={()=>setView('accounts')} className={view==='accounts'?'selected':''}><Users size={18}/>People & access</button><button onClick={()=>setOld(true)}><ArrowLeft size={18}/>Meetings & staff</button></>}</nav><div className="sidebar-bottom"><button className="password-link" onClick={()=>setPassword(true)}>Set / change password</button><div className="identity"><span>{data.self.name}<small>{data.self.is_manager?'SHL':data.self.is_ca?'Community Ambassador':'Employee'}{data.self.is_admin?' · IT Admin':''}</small></span><button aria-label="Sign out" onClick={()=>void signOut()}><LogOut size={18}/></button></div></div></aside><main><header className="topbar"><span>Team workspace / {view}</span><div className="actions"><button className="mobile-password" onClick={()=>setPassword(true)}>Password</button><button className="mobile-password" onClick={()=>void signOut()}>Sign out</button><button aria-label="Refresh workspace" disabled={busy} onClick={()=>void load().catch(()=>{})}><RefreshCw size={18}/></button></div></header><div className="content">{preview&&<div className="preview-banner">DISCONNECTED DEMO · No live changes or emails <select aria-label="Preview role" value={role} onChange={e=>{setRole(e.target.value);setView('schedule')}}><option value="manager">Manager preview</option><option value="ca">CA preview</option><option value="employee">Employee preview</option></select></div>}<div className="page-title"><div><p className="eyebrow">MISSION BBQ · CENTRAL TIME</p><h1>{titles[view]}</h1><p className="muted">{view==='schedule'?data.self.is_manager?'Plan privately. Release when your team is ready.':'Your published work schedule, all in one place.':view==='training'?'Every job gets its own progress and manager sign-off.':''}</p></div></div>{notice&&<p className="success" role="status">{notice}</p>}{error&&!training&&<p className="error" role="alert">{error}</p>}
 {view==='schedule'&&<><ScheduleBoard data={data} week={week} setWeek={setWeek} act={act} busy={busy} onTraining={revision=>setTraining({revision})}/><section className="panel scheduler-card"><h2>Your upcoming commitments</h2>{data.appointments.filter(a=>a.status==='Scheduled').map(a=><p key={a.id}><strong>Meeting · {displayTime(a.scheduled_at)}</strong><br/>{a.employee} with {a.manager}</p>)}{data.training.filter(t=>t.status==='Scheduled'&&(t.staff_id===data.self.staff_id||t.trainer_id===data.self.staff_id)).map(t=><p key={t.id}><strong>Training · {displayTime(t.scheduled_at)}</strong><br/>{data.people.find(p=>p.staff_id===t.trainer_id)?.name} Training {data.people.find(p=>p.staff_id===t.staff_id)?.name}</p>)}{!data.appointments.some(a=>a.status==='Scheduled')&&!data.training.some(t=>t.status==='Scheduled'&&(t.staff_id===data.self.staff_id||t.trainer_id===data.self.staff_id))&&<p className="muted">No personal meetings or training currently scheduled.</p>}</section></>}
 {view==='availability'&&<ScheduleRequests key="availability" data={data} act={act} busy={busy} availabilityOnly/>}{view==='requests'&&<ScheduleRequests key="requests" data={data} act={act} busy={busy}/>}{view==='announcements'&&<Announcements data={data} act={act} busy={busy}/>}{view==='accounts'&&data.self.is_manager&&<SchedulerAccounts data={data} act={act} busy={busy} reload={load} preview={preview}/>}{view==='training'&&<SchedulerTraining data={data} act={act} busy={busy} onReload={load} preview={preview} onSchedule={()=>setTraining({})} onEdit={initial=>setTraining({initial,revision:initial.schedule_revision_id===data.week.draft?.id?initial.schedule_revision_id:undefined})}/>}
 <footer>MISSION BBQ · Team workspace<span>America/Chicago · Published schedules only for employees</span></footer></div></main>{training&&<Modal title={training.initial?'Edit training':'Schedule training'} busy={busy} onClose={()=>{setTraining(null);setError('')}}><TrainingForm data={data} revision={training.revision} initial={training.initial} busy={busy} error={error} onSave={p=>act('training_save',{...p,...(training.initial?{id:training.initial.id,version:training.initial.version}:{})}).then(()=>setTraining(null)).catch(()=>{})}/></Modal>}</div>
}
