-- Display-only correction; no employee records or permissions change.
begin;
create or replace function public.operations_read(p_module text,p_view text,p_offset int default 0,p_search text default '') returns jsonb language plpgsql stable security definer set search_path='' as $$
declare manager boolean:=p_view<>'employee' and private.is_manager();items jsonb;total bigint;person text:=private.my_person();g text;own_contact jsonb;
begin
 if not private.scheduler_member() then raise exception 'Active workspace access required';end if;
 if p_view not in ('employee','manager','it') or p_view is null or p_view='manager' and not private.is_manager() or p_view='it' and not private.is_admin() then raise exception 'Workspace access required';end if;
 if p_offset<0 or p_offset is null then raise exception 'Invalid page';end if;
 if p_module in ('logbook','labor','reports','brief') and not manager then raise exception 'Manager workspace required';end if;
 if p_module='directory' then
  select count(*) into total from (select 's:'||id id,first_name||' '||last_name name from public.staff where active union all select 'm:'||id::text,name from public.manager_profiles where active and on_roster and linked_staff_id is null) x where x.name ilike '%'||p_search||'%';
  select coalesce(jsonb_agg(v),'[]') into items from (select jsonb_build_object('person_id',x.id,'name',x.name,'group',x.g,'job',x.job,'trainer',x.trainer,'version',case when x.id=person then coalesce(c.version,0) end,'phone',case when manager or x.id=person or c.share_phone then c.phone end,'email',case when manager or x.id=person or c.share_email then c.email end,'share_phone',case when x.id=person then coalesce(c.share_phone,false) end,'share_email',case when x.id=person then coalesce(c.share_email,false) end,'emergency_name',case when manager or x.id=person then c.emergency_name end,'emergency_phone',case when manager or x.id=person then c.emergency_phone end,'birthday_month',c.birthday_month,'birthday_day',c.birthday_day) v from (select 's:'||s.id id,s.first_name||' '||s.last_name name,coalesce(private.staff_shl_code(s.id),case when private.person_is_shl('s:'||s.id) and private.person_employment('s:'||s.id)='Salaried' then 'sSHL' when private.person_is_shl('s:'||s.id) and private.person_employment('s:'||s.id)='Hourly' then 'hSHL' else s.department end) g,case when private.staff_shl_code(s.id)='sSHL' or private.person_is_shl('s:'||s.id) and private.person_employment('s:'||s.id)='Salaried' then 'sSHL' else j.name end job,s.is_trainer trainer from public.staff s left join public.training_positions j on j.id=s.primary_job_id where s.active union all select 'm:'||id::text,name,case employment_type when 'Hourly' then 'hSHL' when 'Salaried' then 'sSHL' else 'SHL' end,case when employment_type='Salaried' then 'sSHL' else null end,false from public.manager_profiles where active and on_roster and linked_staff_id is null) x left join private.person_contacts c on c.person_id=x.id where x.name ilike '%'||p_search||'%' order by x.name,x.id limit 50 offset p_offset) z;
 elsif p_module='brief' then
  return jsonb_build_object('appointments',(select coalesce(jsonb_agg(jsonb_build_object('id',a.id,'scheduled_at',a.scheduled_at,'employee',s.first_name||' '||s.last_name,'manager',m.name,'type',a.type) order by a.scheduled_at),'[]') from public.meetings a join public.staff s on s.id=a.staff_id join public.manager_profiles m on m.id=a.manager_id where a.status='Scheduled' and (a.scheduled_at at time zone 'America/Chicago')::date=(now() at time zone 'America/Chicago')::date),'reminders',(select coalesce(jsonb_agg(to_jsonb(l)||jsonb_build_object('assignee',private.account_name(l.assigned_to))),'[]') from private.logbook l where not l.archived and l.completed_at is null and l.due_on<=(now() at time zone 'America/Chicago')::date),'birthdays',(select coalesce(jsonb_agg(jsonb_build_object('name',private.person_name(c.person_id))),'[]') from private.person_contacts c where private.person_active(c.person_id) and c.birthday_month=extract(month from now() at time zone 'America/Chicago') and c.birthday_day=extract(day from now() at time zone 'America/Chicago')));
 elsif p_module='profile' then
  select to_jsonb(c) into own_contact from private.person_contacts c where c.person_id=person;
  return jsonb_build_object('profile',coalesce(own_contact,jsonb_build_object('person_id',person,'version',0)),'calendar_enabled',exists(select 1 from private.calendar_tokens where user_id=auth.uid()));
 elsif p_module='logbook' then
  select count(*) into total from private.logbook where not archived and (title||' '||body) ilike '%'||p_search||'%';
  select coalesce(jsonb_agg(v),'[]') into items from (select to_jsonb(l)||jsonb_build_object('author',private.account_name(l.created_by),'assignee',private.account_name(l.assigned_to),'history',(select coalesce(jsonb_agg(jsonb_build_object('at',a.changed_at,'by',private.account_name(a.actor),'action',a.action,'before',a.before_value,'after',a.after_value)),'[]') from (select * from private.scheduler_audit where record_id=l.id::text and action like 'operations:logbook%' order by id desc limit 30) a)) v from private.logbook l where not archived and (title||' '||body) ilike '%'||p_search||'%' order by entry_date desc,created_at desc,id limit 50 offset p_offset) z;
 elsif p_module='documents' then
  g:=case when private.is_manager() then 'SHL' else (select department from public.staff where id=private.employee_staff()) end;
  select count(*) into total from private.documents d where (manager or d.active and (cardinality(d.groups)=0 or g=any(d.groups))) and d.title ilike '%'||p_search||'%';
  select coalesce(jsonb_agg(v),'[]') into items from (select to_jsonb(d)||jsonb_build_object('file',(select to_jsonb(f) from private.document_versions f where f.document_id=d.id and f.version=d.version),'read',exists(select 1 from private.document_activity a where a.document_id=d.id and a.version=d.version and a.user_id=auth.uid() and a.kind='Read'),'history',case when manager then (select coalesce(jsonb_agg(to_jsonb(h) order by h.version desc),'[]') from private.document_versions h where h.document_id=d.id) else '[]'::jsonb end,'activity',case when manager then (select coalesce(jsonb_agg(to_jsonb(a)||jsonb_build_object('name',private.account_name(a.user_id))),'[]') from (select * from private.document_activity where document_id=d.id order by id desc limit 100) a) else '[]'::jsonb end) v from private.documents d where (manager or d.active and (cardinality(d.groups)=0 or g=any(d.groups))) and d.title ilike '%'||p_search||'%' order by d.created_at desc,d.id limit 50 offset p_offset) z;
 elsif p_module='labor' then
  return jsonb_build_object('rates',(select coalesce(jsonb_agg(to_jsonb(r)),'[]') from private.pay_rates r),'forecasts',(select coalesce(jsonb_agg(to_jsonb(f)),'[]') from private.sales_forecasts f),'can_edit_rates',private.is_admin() or private.is_gm());
 elsif p_module='reports' then
  return jsonb_build_object('meetings',(select coalesce(jsonb_agg(jsonb_build_object('staff_id',s.id,'name',s.first_name||' '||s.last_name,'group',s.department,'last_completed',m.last_completed,'due_on',case when m.last_completed is null then null else (m.last_completed+interval '6 months')::date end)),'[]') from public.staff s left join lateral (select max(completed_on) last_completed from public.meetings where staff_id=s.id and status='Completed') m on true where s.active and not exists(select 1 from public.manager_profiles mp where mp.active and mp.linked_staff_id=s.id)));
 else raise exception 'Unknown module';end if;
 return jsonb_build_object('items',items,'total',total,'offset',p_offset,'limit',50);
end $$;
commit;
