begin;
-- Public location names only; account and operational data remain private.
create table private.login_stores(code text primary key,state text not null,name text not null);
alter table private.login_stores enable row level security;
revoke all on private.login_stores from public,anon,authenticated;
insert into private.login_stores(code,state,name) values
('glendale-az-arrowhead-towne-center','Arizona','Glendale, AZ (Arrowhead Towne Center)'),
('goodyear-az','Arizona','Goodyear, AZ'),
('paradise-valley-az','Arizona','Paradise Valley, AZ'),
('surprise-az','Arizona','Surprise, AZ'),
('arvada-co','Colorado','Arvada, CO'),
('colorado-springs-co-interquest-pkwy','Colorado','Colorado Springs, CO (Interquest Pkwy)'),
('orange-ct','Connecticut','Orange, CT'),
('southington-ct','Connecticut','Southington, CT'),
('dover-de','Delaware','Dover, DE'),
('rehoboth-beach-de','Delaware','Rehoboth Beach, DE'),
('wilmington-de-concord-pike','Delaware','Wilmington, DE (Concord Pike)'),
('wilmington-de-kirkwood-highway','Delaware','Wilmington, DE (Kirkwood Highway)'),
('boynton-beach-fl','Florida','Boynton Beach, FL'),
('bradenton-fl','Florida','Bradenton, FL'),
('brandon-fl','Florida','Brandon, FL'),
('brooksville-fl','Florida','Brooksville, FL'),
('cape-coral-fl','Florida','Cape Coral, FL'),
('clermont-fl','Florida','Clermont, FL'),
('davie-fl','Florida','Davie, FL'),
('davie-fl-weston','Florida','Davie, FL (Weston)'),
('doral-fl','Florida','Doral, FL'),
('fort-lauderdale-fl','Florida','Fort Lauderdale, FL'),
('fort-myers-fl','Florida','Fort Myers, FL'),
('jacksonville-fl-orange-park','Florida','Jacksonville, FL (Orange Park)'),
('jacksonville-fl-st-john-s','Florida','Jacksonville, FL (St. John’s)'),
('lady-lake-fl','Florida','Lady Lake, FL'),
('lakeland-fl','Florida','Lakeland, FL'),
('lake-mary-fl','Florida','Lake Mary, FL'),
('land-o-lakes-fl-lutz','Florida','Land O’Lakes, FL (Lutz)'),
('mount-dora-fl','Florida','Mount Dora, FL'),
('naples-fl','Florida','Naples, FL'),
('ocala-fl','Florida','Ocala, FL'),
('orlando-fl-lee-vista','Florida','Orlando, FL (Lee Vista)'),
('oviedo-fl','Florida','Oviedo, FL'),
('panama-city-fl','Florida','Panama City, FL'),
('pensacola-fl','Florida','Pensacola, FL'),
('port-charlotte-fl','Florida','Port Charlotte, FL'),
('port-st-lucie-fl','Florida','Port St. Lucie, FL'),
('riverview-fl','Florida','Riverview, FL'),
('royal-palm-beach-fl','Florida','Royal Palm Beach, FL'),
('sarasota-fl','Florida','Sarasota, FL'),
('tallahassee-fl','Florida','Tallahassee, FL'),
('tampa-fl-temple-terrace','Florida','Tampa, FL (Temple Terrace)'),
('tampa-fl-town-country','Florida','Tampa, FL (Town & Country)'),
('downers-grove-il','Illinois','Downers Grove, IL'),
('gurnee-il','Illinois','Gurnee, IL'),
('naperville-il','Illinois','Naperville, IL'),
('peoria-il','Illinois','Peoria, IL'),
('rockford-il','Illinois','Rockford, IL'),
('springfield-il','Illinois','Springfield, IL'),
('clarksville-in','Indiana','Clarksville, IN'),
('evansville-in','Indiana','Evansville, IN'),
('fort-wayne-in','Indiana','Fort Wayne, IN'),
('merrillville-in','Indiana','Merrillville, IN'),
('mishawaka-in','Indiana','Mishawaka, IN'),
('davenport-ia','Iowa','Davenport, IA'),
('bowling-green-ky','Kentucky','Bowling Green, KY'),
('st-matthews-ky','Kentucky','St. Matthews, KY'),
('annapolis-md-town-center','Maryland','Annapolis, MD (Town Center)'),
('baltimore-md-canton','Maryland','Baltimore, MD (Canton)'),
('bel-air-md','Maryland','Bel Air, MD'),
('california-md','Maryland','California, MD'),
('columbia-md','Maryland','Columbia, MD'),
('ellicott-city-md','Maryland','Ellicott City, MD'),
('frederick-md','Maryland','Frederick, MD'),
('gambrills-md','Maryland','Gambrills, MD'),
('germantown-md','Maryland','Germantown, MD'),
('glen-burnie-md','Maryland','Glen Burnie, MD'),
('greenbelt-md','Maryland','Greenbelt, MD'),
('hagerstown-md','Maryland','Hagerstown, MD'),
('hunt-valley-md','Maryland','Hunt Valley, MD'),
('laurel-md','Maryland','Laurel, MD'),
('owings-mills-md','Maryland','Owings Mills, MD'),
('perry-hall-md','Maryland','Perry Hall, MD'),
('rockville-md','Maryland','Rockville, MD'),
('salisbury-md','Maryland','Salisbury, MD'),
('towson-md','Maryland','Towson, MD'),
('waldorf-md','Maryland','Waldorf, MD'),
('westminster-md','Maryland','Westminster, MD'),
('grand-rapids-mi','Michigan','Grand Rapids, MI'),
('northville-mi','Michigan','Northville, MI'),
('sterling-heights-mi','Michigan','Sterling Heights, MI'),
('troy-mi','Michigan','Troy, MI'),
('henderson-nv','Nevada','Henderson, NV'),
('cherry-hill-nj','New Jersey','Cherry Hill, NJ'),
('deptford-nj','New Jersey','Deptford, NJ'),
('hamilton-nj','New Jersey','Hamilton, NJ'),
('marlton-nj','New Jersey','Marlton, NJ'),
('sicklerville-nj','New Jersey','Sicklerville, NJ'),
('albany-ny-colonie','New York','Albany, NY (Colonie)'),
('amherst-ny','New York','Amherst, NY'),
('henrietta-ny','New York','Henrietta, NY'),
('fayetteville-nc','North Carolina','Fayetteville, NC'),
('greenville-nc','North Carolina','Greenville, NC'),
('jacksonville-nc','North Carolina','Jacksonville, NC'),
('raleigh-nc','North Carolina','Raleigh, NC'),
('wilmington-nc','North Carolina','Wilmington, NC'),
('boardman-oh','Ohio','Boardman, OH'),
('brunswick-oh','Ohio','Brunswick, OH'),
('canton-oh','Ohio','Canton, OH'),
('dayton-oh','Ohio','Dayton, OH'),
('mason-oh','Ohio','Mason, OH'),
('mentor-oh','Ohio','Mentor, OH'),
('niles-oh','Ohio','Niles, OH'),
('parma-oh','Ohio','Parma, OH'),
('westlake-oh','Ohio','Westlake, OH'),
('tulsa-ok','Oklahoma','Tulsa, OK'),
('oklahoma-city-ok-quail-springs','Oklahoma','Oklahoma City, OK (Quail Springs)'),
('camp-hill-pa','Pennsylvania','Camp Hill, PA'),
('cranberry-township-pa','Pennsylvania','Cranberry Township, PA'),
('harrisburg-pa','Pennsylvania','Harrisburg, PA'),
('king-of-prussia-pa','Pennsylvania','King of Prussia, PA'),
('lancaster-pa','Pennsylvania','Lancaster, PA'),
('monroeville-pa','Pennsylvania','Monroeville, PA'),
('oxford-valley-pa','Pennsylvania','Oxford Valley, PA'),
('pittsburgh-pa-robinson-twp','Pennsylvania','Pittsburgh, PA (Robinson Twp.)'),
('plymouth-meeting-pa','Pennsylvania','Plymouth Meeting, PA'),
('springfield-pa','Pennsylvania','Springfield, PA'),
('warminster-pa','Pennsylvania','Warminster, PA'),
('whitehall-pa','Pennsylvania','Whitehall, PA'),
('wilkes-barre-pa','Pennsylvania','Wilkes Barre, PA'),
('wyomissing-pa','Pennsylvania','Wyomissing, PA'),
('york-pa','Pennsylvania','York, PA'),
('columbia-sc','South Carolina','Columbia, SC'),
('north-myrtle-beach-sc','South Carolina','North Myrtle Beach, SC'),
('chattanooga-tn','Tennessee','Chattanooga, TN'),
('clarksville-tn','Tennessee','Clarksville, TN'),
('murfreesboro-tn','Tennessee','Murfreesboro, TN'),
('nashville-tn-opry-mills','Tennessee','Nashville, TN (Opry Mills)'),
('riverdale-ut','Utah','Riverdale, UT'),
('alexandria-va','Virginia','Alexandria, VA'),
('chantilly-va','Virginia','Chantilly, VA'),
('charlottesville-va','Virginia','Charlottesville, VA'),
('chesapeake-va','Virginia','Chesapeake, VA'),
('christiansburg-va','Virginia','Christiansburg, VA'),
('colonial-heights-va','Virginia','Colonial Heights, VA'),
('fredericksburg-va','Virginia','Fredericksburg, VA'),
('gainesville-va','Virginia','Gainesville, VA'),
('hampton-va','Virginia','Hampton, VA'),
('herndon-va','Virginia','Herndon, VA'),
('lynchburg-va','Virginia','Lynchburg, VA'),
('midlothian-va','Virginia','Midlothian, VA'),
('midlothian-va-hull-street','Virginia','Midlothian, VA (Hull Street)'),
('newport-news-va','Virginia','Newport News, VA'),
('norfolk-va-lake-wright','Virginia','Norfolk, VA (Lake Wright)'),
('richmond-va','Virginia','Richmond, VA'),
('roanoke-va','Virginia','Roanoke, VA'),
('stafford-va','Virginia','Stafford, VA'),
('sterling-va','Virginia','Sterling, VA'),
('virginia-beach-va','Virginia','Virginia Beach, VA'),
('winchester-va','Virginia','Winchester, VA'),
('woodbridge-va','Virginia','Woodbridge, VA'),
('brookfield-wi','Wisconsin','Brookfield, WI'),
('green-bay-wi','Wisconsin','Green Bay, WI'),
('kenosha-wi','Wisconsin','Kenosha, WI'),
('madison-wi-east','Wisconsin','Madison, WI (East)'),
('west-allis-wi','Wisconsin','West Allis, WI');
-- This backend serves Downers Grove only. Listing another store never enables access.
create function public.login_locations() returns jsonb language sql stable security definer set search_path='' as $$
 select coalesce(jsonb_agg(jsonb_build_object('code',code,'state',state,'name',name,'online',code='downers-grove-il') order by state,name),'[]') from private.login_stores
$$;
create function public.confirm_login_store(p_store text) returns void language plpgsql stable security definer set search_path='' as $$
begin
 if p_store is distinct from 'downers-grove-il' then raise exception 'This store is not online. Choose Downers Grove, Illinois';end if;
 if not private.scheduler_member() then raise exception 'Your account does not have active access to Downers Grove';end if;
end $$;
revoke all on function public.login_locations(),public.confirm_login_store(text) from public,anon,authenticated;
grant execute on function public.login_locations() to anon,authenticated;
grant execute on function public.confirm_login_store(text) to authenticated;
commit;
